"""ParaView export: multiblock geometry, frequency grids, session state.

Three layers:

1. :func:`export_vtm` — tessellate each solid into its own block of a VTK
   multiblock dataset (``geometry.vtm`` + ``geometry/*.vtp``).  Blocks carry
   the shape name and a ``MaterialIndex`` cell array; a categorical lookup
   table colours the blocks per material (colours from
   :func:`~magnelio.post._colors.material_color`, the same palette as the
   built-in 3D viewer).
2. Frequency-monitor export — the ``fields_freq.h5`` DFT bins as one
   rectilinear ``.vtr`` file per frequency plus a ``.pvd`` collection
   (frequency plays the role of the ParaView time axis).  Time monitors
   stay on the XDMF-over-``results.h5`` path — no data duplication.
   Eigenmodes take the same ``.vtr``/``.pvd`` shape one directory up
   (they belong to the project, not to a run), with the *mode index*
   on the ParaView axis — see :func:`export_eigenmode_visualization`.
3. :func:`export_run_visualization` — generates ``paraview_open.py``, a
   ``paraview.simple`` pipeline script (coloured geometry, per-monitor
   slice planes, normalised and magnitude-clipped field glyphs,
   plane-linked geometry clips) and, when ``pvpython`` is on the PATH,
   bakes it into a double-clickable ``paraview.pvsm`` state file.

Everything here is visualization-only: failures must never invalidate a
run, so the store calls into this module behind broad guards.
"""

# Design: DD-115 (three-layer ParaView export pipeline).

from __future__ import annotations

import json
import re
import shutil
import subprocess
import warnings
from pathlib import Path

import numpy as np

# Glyphs are sized so a full-length arrow spans this fraction of the
# monitor's bounding-box diagonal.
_GLYPH_LENGTH_FRACTION = 1.0 / 25.0
# Spatial samples used when estimating the magnitude statistics.
_CAP_MAX_SAMPLES = 1_500_000
_CAP_TIME_SAMPLES = 6
# Cells below this fraction of the peak magnitude do not count towards the
# length reference (PEC interiors, quiet volume).
_LIVE_CELL_FRACTION = 0.01
# Percentile of the field-carrying cells taken as the typical magnitude.
_REFERENCE_PERCENTILE = 60.0
# ... which is drawn at this fraction of the full arrow length.  Fixing
# the pair (reference -> this fraction, cap -> full length) is what the
# glyph length exponent is fitted to.
_REFERENCE_LENGTH_FRACTION = 0.45
_EXPONENT_LIMITS = (0.2, 1.0)
# Volume glyphs drop cells below this fraction of the cap: a whole-domain
# monitor is mostly PEC interior and quiet volume, and filling those with
# short arrows buries the field.  Slice glyphs keep every cell — on a
# single cut the empty regions read as information, not clutter.
_VOLUME_THRESHOLD_FRACTION = 0.02
# Arrows are always placed on an evenly spaced lattice (DD-115 follow-up),
# never on the computational grid.  Two lattices per 3D monitor, because
# the two views need different densities: a cut wants arrows per unit
# AREA, a volume view a bounded total count.
_ARROWS_PER_SECTION = 2000
_RESAMPLE_VOLUME_POINTS = 8000
_RESAMPLE_MAX_PER_AXIS = 300

#: Component axis behind a field-array suffix (``Ey`` -> 1).
_COMP_AXES = {"x": 0, "y": 1, "z": 2}

#: Printed by the session script when it cannot place a mirror plane, and
#: recognised by :func:`bake_pvsm` — the one channel that reaches a
#: caller who never opens ParaView interactively.
_SYMMETRY_MARKER = "MAGNELIO_SYMMETRY_UNAVAILABLE"


def _sanitize(name: str) -> str:
    """File-system-safe token for a monitor / block name."""
    return re.sub(r"[^\w.-]+", "_", name).strip("_") or "unnamed"


def _material_table(materials, colors=None) -> tuple[list[dict], list[int]]:
    """Unique material table and the per-shape index into it.

    Deterministic for a given shape order, so the ``MaterialIndex`` cell
    array written by :func:`export_vtm` and the lookup table generated by
    :func:`export_run_visualization` (which re-derives the table from
    ``geometry.json``) always agree.

    *colors* optionally carries the per-shape display colour imported
    from a CAD file, so two shapes of the same material but different
    file colours become two entries.
    """
    from magnelio.post._colors import material_color  # noqa: PLC0415

    table: list[dict] = []
    index_of: dict = {}
    used_names: set[str] = set()
    indices = []
    if colors is None:
        colors = [None] * len(materials)
    for mat, color in zip(materials, colors):
        rgba = tuple(round(float(c), 6) for c in material_color(mat, color))
        if rgba[3] == 0.0 and getattr(mat, "color", None) is None and getattr(mat, "visible", True):
            # Auto-coloured air/vacuum: the 2D cross-sections draw it as
            # a dashed wall outline, but in 3D the vacuum volume IS the
            # device (a cavity carved into metal) — render it as a light
            # translucent blue instead of not at all.  An explicit
            # Material(color=..., alpha=...) or visible=False still wins.
            rgba = (0.25, 0.5, 1.0, 0.3)
        name = getattr(mat, "name", None) or "material"
        key = (name, rgba)
        if key not in index_of:
            label = name
            n = 2
            while label in used_names:
                label = f"{name} #{n}"
                n += 1
            used_names.add(label)
            index_of[key] = len(table)
            table.append({"name": label, "rgba": list(rgba)})
        indices.append(index_of[key])
    return table, indices


# ═════════════════════════════════════════════════════════════════════
# Geometry: per-solid tessellation -> multiblock .vtm
# ═════════════════════════════════════════════════════════════════════


def _occ_deflection(shape, rel: float) -> float:
    """Linear deflection as a fraction of the shape's bbox diagonal."""
    from OCC.Core.Bnd import Bnd_Box  # noqa: PLC0415

    try:
        from OCC.Core.BRepBndLib import brepbndlib  # noqa: PLC0415

        add = brepbndlib.Add
    except ImportError:  # pragma: no cover - legacy pythonocc naming
        from OCC.Core.BRepBndLib import brepbndlib_Add as add  # noqa: PLC0415

    box = Bnd_Box()
    add(shape, box)
    if box.IsVoid():
        return 1e-4
    xmin, ymin, zmin, xmax, ymax, zmax = box.Get()
    diag = float(np.sqrt((xmax - xmin) ** 2 + (ymax - ymin) ** 2 + (zmax - zmin) ** 2))
    return max(rel * diag, 1e-12)


def _tessellate_shape(occ_shape, deflection: float | None):
    """Triangulate one TopoDS shape into ``(points, triangles)`` arrays.

    Returns ``None`` when the shape yields no triangulation (e.g. an
    empty compound).  Face orientation is honoured so outward normals
    survive into the ``.vtp`` blocks.
    """
    from OCC.Core.BRep import BRep_Tool  # noqa: PLC0415
    from OCC.Core.BRepMesh import BRepMesh_IncrementalMesh  # noqa: PLC0415
    from OCC.Core.TopAbs import TopAbs_FACE, TopAbs_REVERSED  # noqa: PLC0415
    from OCC.Core.TopExp import TopExp_Explorer  # noqa: PLC0415
    from OCC.Core.TopLoc import TopLoc_Location  # noqa: PLC0415
    from OCC.Core.TopoDS import topods  # noqa: PLC0415

    defl = deflection if deflection is not None else _occ_deflection(occ_shape, 2e-3)
    BRepMesh_IncrementalMesh(occ_shape, defl)

    points: list[np.ndarray] = []
    tris: list[np.ndarray] = []
    offset = 0
    exp = TopExp_Explorer(occ_shape, TopAbs_FACE)
    while exp.More():
        face = topods.Face(exp.Current())
        exp.Next()
        loc = TopLoc_Location()
        tri = BRep_Tool.Triangulation(face, loc)
        if tri is None:
            continue
        trsf = loc.Transformation()
        n_nodes = tri.NbNodes()
        pts = np.empty((n_nodes, 3), dtype=np.float64)
        for i in range(1, n_nodes + 1):
            p = tri.Node(i).Transformed(trsf)
            pts[i - 1] = (p.X(), p.Y(), p.Z())
        n_tri = tri.NbTriangles()
        con = np.empty((n_tri, 3), dtype=np.int64)
        reversed_face = face.Orientation() == TopAbs_REVERSED
        for i in range(1, n_tri + 1):
            a, b, c = tri.Triangle(i).Get()
            con[i - 1] = (c, b, a) if reversed_face else (a, b, c)
        points.append(pts)
        tris.append(con - 1 + offset)
        offset += n_nodes
    if not points:
        return None
    return np.vstack(points), np.vstack(tris)


def _polydata(points: np.ndarray, triangles: np.ndarray):
    """Build a ``vtkPolyData`` from point / triangle index arrays."""
    import vtk  # noqa: PLC0415
    from vtk.util import numpy_support as ns  # noqa: PLC0415

    pd = vtk.vtkPolyData()
    vpts = vtk.vtkPoints()
    vpts.SetData(ns.numpy_to_vtk(np.ascontiguousarray(points), deep=True))
    pd.SetPoints(vpts)
    n_tri = triangles.shape[0]
    offsets = np.arange(0, 3 * (n_tri + 1), 3, dtype=np.int64)
    conn = np.ascontiguousarray(triangles, dtype=np.int64).ravel()
    ca = vtk.vtkCellArray()
    ca.SetData(
        ns.numpy_to_vtkIdTypeArray(offsets, deep=True),
        ns.numpy_to_vtkIdTypeArray(conn, deep=True),
    )
    pd.SetPolys(ca)
    return pd


def export_vtm(
    path: str | Path,
    geometry,
    deflection: float | None = None,
) -> list[dict]:
    """Export solids as a per-solid VTK multiblock dataset (``.vtm``).

    Each solid becomes its own named block carrying a constant
    ``MaterialIndex`` cell array (index into the returned material table)
    and the material name as field data, so ParaView can colour blocks
    per material with a categorical lookup table and users can hide or
    extract individual solids.

    Parameters
    ----------
    path : str or Path
        Output file path (``.vtm``; a sibling data directory is created).
    geometry : iterable
        Shape objects exposing ``_occ_shape()`` and ``material`` —
        a :class:`~magnelio.geo.GeometryModel`, a
        :class:`~magnelio.io.project.LoadedGeometry`, or a plain list.
        Thin wires must be filtered out by the caller.
    deflection : float, optional
        Absolute tessellation accuracy [m].  Default: 0.2 % of each
        solid's bounding-box diagonal (scale-independent).

    Returns
    -------
    list of dict
        The material table (``{"name", "rgba"}`` per entry) the block
        colouring refers to.
    """
    import vtk  # noqa: PLC0415
    from vtk.util import numpy_support as ns  # noqa: PLC0415

    shapes = list(geometry)
    table, indices = _material_table(
        [s.material for s in shapes], [getattr(s, "color", None) for s in shapes]
    )

    # DD-120: tessellate at the model scale, convert points to meters.
    geo_scale = 1.0
    if shapes and all(hasattr(s, "_analytic_bbox") for s in shapes):
        from magnelio.geo._scaling import model_scale  # noqa: PLC0415

        geo_scale = model_scale(shapes)

    mb = vtk.vtkMultiBlockDataSet()
    mb.SetNumberOfBlocks(len(shapes))
    used_names: set[str] = set()
    for i, shape in enumerate(shapes):
        name = getattr(shape, "name", None) or f"shape_{i}"
        label = name
        n = 2
        while label in used_names:
            label = f"{name}_{n}"
            n += 1
        used_names.add(label)
        mb.GetMetaData(i).Set(vtk.vtkCompositeDataSet.NAME(), label)

        tess = _tessellate_shape(
            shape._occ_shape(geo_scale),
            None if deflection is None else deflection * geo_scale,
        )
        if tess is None:
            continue
        tess_points, tess_tris = tess
        pd = _polydata(tess_points / geo_scale, tess_tris)
        mat_idx = np.full(pd.GetNumberOfCells(), indices[i], dtype=np.int32)
        arr = ns.numpy_to_vtk(mat_idx, deep=True)
        arr.SetName("MaterialIndex")
        pd.GetCellData().AddArray(arr)
        name_arr = vtk.vtkStringArray()
        name_arr.SetName("MaterialName")
        name_arr.InsertNextValue(table[indices[i]]["name"])
        pd.GetFieldData().AddArray(name_arr)
        mb.SetBlock(i, pd)

    writer = vtk.vtkXMLMultiBlockDataWriter()
    writer.SetFileName(str(path))
    writer.SetInputData(mb)
    writer.Write()
    return table


# ═════════════════════════════════════════════════════════════════════
# Monitors: caps, per-monitor XDMF, frequency .vtr series
# ═════════════════════════════════════════════════════════════════════


def _pick_vector(components) -> tuple[str, list[str]] | None:
    """The preferred complete field triple among *components* (E over H)."""
    comps = set(components)
    for field in ("E", "H"):
        triple = [f"{field}{ax}" for ax in "xyz"]
        if all(c in comps for c in triple):
            return field, triple
    return None


def _mirror_signature(array_name: str) -> tuple[str, int | None] | None:
    """``(field, component axis)`` of an exported field array, or ``None``.

    ``Ex`` and ``Hz_im`` name a single component, ``E`` and ``E_re`` the
    3-component vector (component ``None``).  Magnitudes and anything
    unrecognised give ``None``: they are even across every mirror and
    need no correction.
    """
    stem = array_name
    for suffix in ("_re", "_im"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break
    if stem in ("E", "H"):
        return stem, None
    if len(stem) == 2 and stem[0] in ("E", "H") and stem[1] in _COMP_AXES:
        return stem[0], _COMP_AXES[stem[1]]
    return None


def _mirror_factor(field: str, comp: int | None, mirror_axis: int, kind: str) -> float:
    """Sign the renderer's reflection filter still owes a field array.

    The filter transforms every 3-component array as a polar vector: it
    negates the component along the mirror axis and leaves the other two.
    That is the entire continuation exactly when the normal component is
    the odd one — for the other pairing every component is off by a
    global minus, which is what a vector gets back here.  Single
    components the filter never touches, so they carry their
    continuation factor in full.
    """
    from magnelio.post._symmetry import mirror_sign  # noqa: PLC0415

    if comp is None:
        return -mirror_sign(field, mirror_axis, mirror_axis, kind)
    return mirror_sign(field, comp, mirror_axis, kind)


def _mirror_fixes(array_names, mirrors) -> list[list]:
    """Per mirror plane, the ``[name, factor]`` pairs needing correction.

    Arrays the filter already continues correctly are left out, so a
    plane that needs nothing produces an empty list and stays a single
    reflection rather than a reflect/negate/join branch.
    """
    fixes = []
    for axis, _wall, _at_low, kind in mirrors:
        mirror_axis = _COMP_AXES[axis]
        plane = []
        for name in array_names:
            signature = _mirror_signature(name)
            if signature is None:
                continue
            factor = _mirror_factor(signature[0], signature[1], mirror_axis, kind)
            if factor < 0.0:
                plane.append([name, factor])
        fixes.append(plane)
    return fixes


def _prepare_mirroring(monitors, mirrors) -> None:
    """Resolve each monitor spec against the declared mirror planes.

    Two edits, both in place.  The sign corrections replace the raw array
    listing, and a monitor collapsed onto a mirrored axis gets its second
    sampling layer: mirroring turns its single cell layer into two, and a
    lattice of one would sample the seam between them instead.

    The lattice is deliberately *not* widened otherwise.  Its spacing is
    sized for a target arrow count in the displayed picture, and the
    displayed picture is the mirrored one — keeping the dimensions puts
    that target on the full model rather than on each half.
    """
    for spec in monitors:
        spec["mirror_fix"] = _mirror_fixes(spec.pop("field_arrays", []), mirrors)
        for axis, _wall, _at_low, _kind in mirrors:
            index = _COMP_AXES[axis]
            for key in ("resample_dims", "resample_dims_volume"):
                dims = spec.get(key)
                if dims and dims[index] == 1:
                    dims[index] = 2


def _sample_steps(n: int, k: int = _CAP_TIME_SAMPLES) -> list[int]:
    return sorted(set(np.linspace(0, n - 1, min(k, n)).astype(int).tolist()))


def _spatial_stride(shape) -> tuple[slice, ...]:
    total = int(np.prod(shape))
    if total <= _CAP_MAX_SAMPLES:
        return (slice(None),) * len(shape)
    s = int(np.ceil((total / _CAP_MAX_SAMPLES) ** (1.0 / len(shape))))
    return tuple(slice(None, None, s) for _ in shape)


def _magnitude_stats(component_steps, percentile: float) -> tuple[float, float]:
    """Glyph clip cap and length reference from sampled ``|v|``.

    ``component_steps`` yields, per sampled step, the list of component
    arrays (already spatially subsampled).  Two *different* numbers come
    out of the pooled magnitudes, and conflating them makes the glyphs
    unusable (DD-115 follow-up):

    * **cap** — the high percentile at which arrow length saturates, so
      edge singularities keep their direction without dictating the
      scale.  Taken over all samples.
    * **reference** — the magnitude that maps to the full arrow length.
      Taken over the *field-carrying* cells only (above 1 % of the
      maximum): a monitor spanning the whole domain is typically half
      zeros — PEC interiors and quiet volume — and a percentile over
      those puts the reference next to the maximum, which renders the
      typical arrow sub-millimetre.
    """
    chunks = []
    for comps in component_steps:
        m2 = None
        for a in comps:
            a = np.abs(np.asarray(a, dtype=np.complex128 if np.iscomplexobj(a) else np.float64))
            m2 = a * a if m2 is None else m2 + a * a
        chunks.append(np.sqrt(np.real(m2)).ravel())
    vals = np.concatenate(chunks) if chunks else np.zeros(0)
    if vals.size == 0 or not np.any(vals > 0.0):
        return 0.0, 1.0
    cap = float(np.percentile(vals, percentile))
    live = vals[vals > _LIVE_CELL_FRACTION * vals.max()]
    ref = float(np.percentile(live, _REFERENCE_PERCENTILE)) if live.size else cap
    if cap <= 0.0:
        return 0.0, 1.0
    return cap, _length_exponent(ref, cap)


def _length_exponent(reference: float, cap: float) -> float:
    """Exponent mapping *reference* to a fixed fraction of the full length.

    The glyph length factor is ``(m/cap) ** exponent``.  Solving
    ``(reference/cap) ** e == _REFERENCE_LENGTH_FRACTION`` puts the
    typical field-carrying magnitude at a visible length while the cap
    still maps to exactly 1, so the longest arrow stays bounded.  A
    linear map falls out (exponent 1) when the reference already sits at
    that fraction; heavier-tailed distributions compress harder.
    """
    lo, hi = _EXPONENT_LIMITS
    if not 0.0 < reference < cap:
        return hi
    e = float(np.log(_REFERENCE_LENGTH_FRACTION) / np.log(reference / cap))
    return float(min(max(e, lo), hi))


def _monitor_geometry(node_x, node_y, node_z) -> dict:
    """Slice-plane spec derived from a monitor's node coordinates."""
    nodes = [np.asarray(node_x), np.asarray(node_y), np.asarray(node_z)]
    ext = [float(a[-1] - a[0]) for a in nodes]
    center = [float(0.5 * (a[0] + a[-1])) for a in nodes]
    ncells = [len(a) - 1 for a in nodes]
    axes = ["x", "y", "z"]
    degenerate = [ax for ax, n in zip(axes, ncells) if n <= 1]
    diag = float(np.sqrt(sum(e * e for e in ext)))
    # A single-cell axis is degenerate for the lattice even though it has
    # a physical thickness: a plane monitor must resample to one layer,
    # not to several through a thickness that carries no second sample.
    lat_ext = [0.0 if n <= 1 else e for e, n in zip(ext, ncells)]
    spec = {
        "center": center,
        "slice_axes": [],
        "default_axis": None,
        "planar_normal": None,
        "resample_dims": _lattice_dims(lat_ext, _section_step(lat_ext)),
        "resample_dims_volume": None,
        "l_ref": max(diag * _GLYPH_LENGTH_FRACTION, 1e-12),
    }
    if not degenerate:
        spec["slice_axes"] = axes
        # Cutting normal to the shortest extent exposes the largest
        # section area — the natural first view of a 3D monitor.
        spec["default_axis"] = axes[int(np.argmin(ext))]
        step = _volume_step(lat_ext)
        if step:
            spec["resample_dims_volume"] = _lattice_dims(lat_ext, step)
    elif len(degenerate) == 1:
        spec["planar_normal"] = degenerate[0]
    return spec


def _lattice_dims(extents, step: float) -> list[int]:
    """Grid dimensions for *step* spacing; degenerate axes collapse to 1.

    One spacing for every axis, deliberately: a fixed sample count per
    axis would make the spacing directional on an elongated region —
    exactly the bias that placing arrows on the computational grid
    produced in the first place.
    """
    return [
        1 if e <= 0.0 else int(min(max(round(e / step) + 1, 2), _RESAMPLE_MAX_PER_AXIS))
        for e in extents
    ]


def _section_step(extents) -> float:
    """Lattice spacing giving ~``_ARROWS_PER_SECTION`` arrows in a cut.

    Sized from the *largest* section through the region (the plane
    spanning the two longest extents, which is also the default cut), so
    that view lands on the target and the narrower cuts scale down with
    their own area rather than being starved.
    """
    live = sorted((float(e) for e in extents if e > 0.0), reverse=True)
    if len(live) < 2:
        return live[0] / 8.0 if live else 1.0
    return float(np.sqrt(live[0] * live[1] / _ARROWS_PER_SECTION))


def _volume_step(extents) -> float | None:
    """Lattice spacing for a bounded arrow count in the volume view."""
    live = [float(e) for e in extents if e > 0.0]
    if len(live) < 3:
        return None
    return float((live[0] * live[1] * live[2] / _RESAMPLE_VOLUME_POINTS) ** (1.0 / 3.0))


def _export_time_monitor(run_dir: Path, pv_dir: Path, name: str, percentile: float):
    """Per-monitor XDMF (over ``results.h5``) + pipeline spec, or ``None``."""
    import h5py  # noqa: PLC0415

    from magnelio.io.xdmf import _vector_groups, write_run_xdmf  # noqa: PLC0415

    with h5py.File(run_dir / "results.h5", "r", swmr=True) as f:
        mg = f["monitors"][name]
        components = json.loads(mg.attrs["components"])
        times = mg["times"][()]
        n = int(times.shape[0])
        if n == 0:
            return None
        gx, gy, gz = mg["grid_x"][()], mg["grid_y"][()], mg["grid_z"][()]
        vec = _pick_vector(components)
        cap, exponent = 0.0, 1.0
        if vec is not None:
            sl = _spatial_stride(mg[vec[1][0]].shape[1:])

            def steps():
                for ti in _sample_steps(n):
                    yield [mg[c][ti][sl] for c in vec[1]]

            cap, exponent = _magnitude_stats(steps(), percentile)

    safe = _sanitize(name)
    write_run_xdmf(
        pv_dir / f"{safe}.xdmf",
        "../results.h5",
        [
            {
                "name": name,
                "n": n,
                "nx": len(gx) - 1,
                "ny": len(gy) - 1,
                "nz": len(gz) - 1,
                "components": components,
                "times": times,
            }
        ],
    )

    spec = _monitor_geometry(gx, gy, gz)
    spec.update(
        {
            "name": name,
            "kind": "time",
            "data": f"paraview/{safe}.xdmf",
            "reader": "xdmf",
            "glyph": None,
            "field_arrays": list(components) + [n for n, _ds in _vector_groups(components)],
        }
    )
    if vec is not None and cap > 0.0:
        spec["glyph"] = {
            "arrays": [vec[0]],
            "cap": cap,
            "exponent": exponent,
            "length": spec["l_ref"],
            "threshold": cap * _VOLUME_THRESHOLD_FRACTION,
        }
    return spec


def _freq_region_nodes(corners_arr, grid):
    """Node coordinates for a frequency monitor's stored region.

    ``fields_freq.h5`` stores cell-centre axes; the ``.vtr`` cells need
    node coordinates, recovered exactly by re-resolving the stored
    corners against the stored mesh grid (deterministic, DD-104).
    """
    from magnelio.monitors.base import _corners_from_array, resolve_region  # noqa: PLC0415

    region = resolve_region(_corners_from_array(corners_arr), grid)
    return (
        grid.x[region.ix.start : region.ix.stop + 1],
        grid.y[region.iy.start : region.iy.stop + 1],
        grid.z[region.iz.start : region.iz.stop + 1],
    )


def _freq_vtr_grid(node_x, node_y, node_z):
    import vtk  # noqa: PLC0415
    from vtk.util import numpy_support as ns  # noqa: PLC0415

    rg = vtk.vtkRectilinearGrid()
    rg.SetDimensions(len(node_x), len(node_y), len(node_z))
    setters = (rg.SetXCoordinates, rg.SetYCoordinates, rg.SetZCoordinates)
    for axis, nodes, setter in zip("xyz", (node_x, node_y, node_z), setters):
        arr = ns.numpy_to_vtk(np.asarray(nodes, dtype=np.float64), deep=True)
        # Unnamed VTK arrays are written as "Array 0x<address>", which
        # makes the file differ between processes for identical data.
        # Naming them keeps the export byte-reproducible.
        arr.SetName(f"{axis}_nodes")
        setter(arr)
    return rg


def _flat_cells(a: np.ndarray) -> np.ndarray:
    """Monitor-native ``(nx, ny, nz)`` -> VTK cell order (x fastest)."""
    return np.ascontiguousarray(a.transpose(2, 1, 0)).ravel()


def _run_source_spectrum(run_dir: Path, freqs: np.ndarray):
    """The run's excitation transformed at *freqs*, or ``None`` if absent.

    Reads through the store's own run reader rather than reaching into
    ``results.h5``: that reader truncates every stream to their common
    prefix, so a run cut short yields the same waveform here as it does
    through :class:`~magnelio.io.project.Project` — and therefore the
    same spectrum, to the last bit.
    """
    from magnelio.io.project import _read_run_results  # noqa: PLC0415
    from magnelio.monitors._dft import source_spectrum  # noqa: PLC0415

    try:
        sig = _read_run_results(run_dir)["reference"]
    except (OSError, KeyError):
        return None
    return source_spectrum(sig.values, sig.dt, freqs)


def _export_freq_monitor(run_dir: Path, pv_dir: Path, name: str, grid, percentile: float):
    """``.vtr``-per-frequency series + ``.pvd`` collection + pipeline spec."""
    import h5py  # noqa: PLC0415
    import vtk  # noqa: PLC0415
    from vtk.util import numpy_support as ns  # noqa: PLC0415

    from magnelio.monitors._dft import divide_by_spectrum  # noqa: PLC0415

    with h5py.File(run_dir / "fields_freq.h5", "r") as f:
        g = f[name]
        components = json.loads(g.attrs["components"])
        freqs = np.asarray(g["freqs"][()], dtype=float)
        corners = g["corners"][()]
        bins = {c: g["bins"][c][()] for c in components}
    if freqs.size == 0 or not components:
        return None
    # Ship the same quantity the monitor's own ``.data`` reports — fields
    # per 1 W CW — so a value read off the renderer means what a value
    # read in Python means.  A run without a stored excitation (none in
    # practice) exports the raw bins rather than nothing.
    spectrum = _run_source_spectrum(run_dir, freqs)
    if spectrum is not None:
        bins = {c: divide_by_spectrum(v, spectrum) for c, v in bins.items()}

    node_x, node_y, node_z = _freq_region_nodes(corners, grid)
    first = bins[components[0]]
    if first.shape[1:] != (len(node_x) - 1, len(node_y) - 1, len(node_z) - 1):
        return None  # stored grid no longer matches the bins; skip quietly

    safe = _sanitize(name)
    mon_dir = pv_dir / safe
    mon_dir.mkdir(parents=True, exist_ok=True)

    vec = _pick_vector(components)
    entries = []
    for fi, f_val in enumerate(freqs):
        rg = _freq_vtr_grid(node_x, node_y, node_z)
        cd = rg.GetCellData()

        def add(name_, data):
            arr = ns.numpy_to_vtk(np.ascontiguousarray(data, dtype=np.float64), deep=True)
            arr.SetName(name_)
            cd.AddArray(arr)

        for c in components:
            a = bins[c][fi]
            add(f"{c}_re", _flat_cells(a.real))
            add(f"{c}_im", _flat_cells(a.imag))
        if vec is not None:
            field, triple = vec
            re = np.stack([_flat_cells(bins[c][fi].real) for c in triple], axis=-1)
            im = np.stack([_flat_cells(bins[c][fi].imag) for c in triple], axis=-1)
            add(f"{field}_re", re)
            add(f"{field}_im", im)
            add(f"|{field}|", np.sqrt(np.sum(re * re + im * im, axis=-1)))

        writer = vtk.vtkXMLRectilinearGridWriter()
        rel = f"{safe}/f_{fi:04d}.vtr"
        writer.SetFileName(str(pv_dir / rel))
        writer.SetInputData(rg)
        writer.Write()
        entries.append((f_val, rel))

    pvd_lines = [
        '<?xml version="1.0"?>',
        '<VTKFile type="Collection" version="0.1">',
        "  <Collection>",
    ]
    pvd_lines += [
        f'    <DataSet timestep="{f_val:.9e}" part="0" file="{rel}"/>' for f_val, rel in entries
    ]
    pvd_lines += ["  </Collection>", "</VTKFile>", ""]
    (pv_dir / f"{safe}.pvd").write_text("\n".join(pvd_lines), encoding="utf-8")

    field_arrays = [f"{c}_{part}" for c in components for part in ("re", "im")]
    if vec is not None:
        field_arrays += [f"{vec[0]}_re", f"{vec[0]}_im"]
    spec = _monitor_geometry(node_x, node_y, node_z)
    spec.update(
        {
            "name": name,
            "kind": "freq",
            "data": f"paraview/{safe}.pvd",
            "reader": "pvd",
            "glyph": None,
            "field_arrays": field_arrays,
        }
    )
    if vec is not None:
        field, triple = vec
        sl = _spatial_stride(first.shape[1:])

        def steps():
            for fi in _sample_steps(len(freqs)):
                yield [bins[c][fi][sl] for c in triple]

        cap, exponent = _magnitude_stats(steps(), percentile)
        if cap > 0.0:
            # Real and imaginary part each get their own glyph set: they
            # are the field at phase 0 and at phase −90°, and together
            # they span the full ellipse — where one nearly vanishes the
            # other carries the field, so offering only the real part
            # hides half the picture.  Both share the cap and reference
            # from the complex magnitude, which bounds either phase.
            spec["glyph"] = {
                "arrays": [f"{field}_re", f"{field}_im"],
                "cap": cap,
                "exponent": exponent,
                "length": spec["l_ref"],
                "threshold": cap * _VOLUME_THRESHOLD_FRACTION,
            }
    return spec


def _eigenmode_fields(mode_arrays: dict, grid):
    """One stored eigenmode as cell-centred E and H, peak-normalised.

    The stored arrays are the solver's FIT grid quantities (edge
    voltages / face currents), so they go through the same
    ``_interp_to_cell_centres`` conversion the field monitors use
    (DD-085).  An eigenvector carries no absolute amplitude — the
    solver's own scaling ran to 1e8 on the tutorial-13 cavity, which
    reads as V/m and is not — so each field is divided by its own peak
    magnitude.  The two divisors are returned with the fields: they are
    the only thing lost, and writing them into the file keeps the
    normalisation reversible.
    """
    from magnelio._fields.field_arrays import FieldState  # noqa: PLC0415
    from magnelio.monitors.base import _interp_to_cell_centres  # noqa: PLC0415

    state = FieldState(**mode_arrays)
    cells = _interp_to_cell_centres(
        state,
        ["Ex", "Ey", "Ez", "Hx", "Hy", "Hz"],
        slice(0, grid.Nx),
        slice(0, grid.Ny),
        slice(0, grid.Nz),
        grid,
    )
    scales = {}
    for field in ("E", "H"):
        triple = [cells[f"{field}{ax}"] for ax in "xyz"]
        peak = float(np.sqrt(sum(np.asarray(c, dtype=float) ** 2 for c in triple)).max())
        scales[field] = peak if peak > 0.0 else 1.0
        for ax in "xyz":
            cells[f"{field}{ax}"] = np.asarray(cells[f"{field}{ax}"], dtype=float) / scales[field]
    return cells, scales


def _export_eigenmodes(project_path: Path, pv_dir: Path, grid, percentile: float):
    """``.vtr``-per-mode series + ``.pvd`` collection + pipeline spec.

    The ParaView axis carries the **mode index**, not the eigenfrequency:
    degenerate pairs share a frequency to the last digit (they are the
    rule, not the exception, in any symmetric cavity), and two datasets
    at one timestep hide each other.  The frequency travels as field
    data instead, so it is still displayed and still exact.
    """
    import h5py  # noqa: PLC0415
    import vtk  # noqa: PLC0415
    from vtk.util import numpy_support as ns  # noqa: PLC0415

    src = project_path / "eigenmodes.h5"
    if not src.exists():
        return None
    comps = ["Ex", "Ey", "Ez", "Hx", "Hy", "Hz"]
    with h5py.File(src, "r") as f:
        freqs = np.asarray(f["frequencies"][()], dtype=float)
        raw = [{c: f[f"mode_{i:03d}"][c][()] for c in comps} for i in range(freqs.size)]
    if freqs.size == 0:
        return None

    node_x, node_y, node_z = np.asarray(grid.x), np.asarray(grid.y), np.asarray(grid.z)
    mon_dir = pv_dir / "eigenmodes"
    mon_dir.mkdir(parents=True, exist_ok=True)

    entries = []
    cell_fields = []
    for i, mode_arrays in enumerate(raw):
        cells, scales = _eigenmode_fields(mode_arrays, grid)
        cell_fields.append(cells)
        rg = _freq_vtr_grid(node_x, node_y, node_z)
        cd = rg.GetCellData()
        for c in comps:
            arr = ns.numpy_to_vtk(_flat_cells(cells[c]), deep=True)
            arr.SetName(c)
            cd.AddArray(arr)
        for field in ("E", "H"):
            vec = np.stack([_flat_cells(cells[f"{field}{ax}"]) for ax in "xyz"], axis=-1)
            arr = ns.numpy_to_vtk(np.ascontiguousarray(vec), deep=True)
            arr.SetName(field)
            cd.AddArray(arr)
            mag = ns.numpy_to_vtk(np.sqrt(np.sum(vec * vec, axis=-1)), deep=True)
            mag.SetName(f"|{field}|")
            cd.AddArray(mag)
        # Provenance of this file, and the inverse of the normalisation.
        for label, value in (
            ("f_Hz", float(freqs[i])),
            ("mode_index", float(i)),
            ("E_peak_before_normalisation", scales["E"]),
            ("H_peak_before_normalisation", scales["H"]),
        ):
            fd = ns.numpy_to_vtk(np.array([value], dtype=np.float64), deep=True)
            fd.SetName(label)
            rg.GetFieldData().AddArray(fd)

        writer = vtk.vtkXMLRectilinearGridWriter()
        rel = f"eigenmodes/mode_{i:04d}.vtr"
        writer.SetFileName(str(pv_dir / rel))
        writer.SetInputData(rg)
        writer.Write()
        entries.append(rel)

    pvd_lines = [
        '<?xml version="1.0"?>',
        '<VTKFile type="Collection" version="0.1">',
        "  <Collection>",
    ]
    pvd_lines += [
        f'    <DataSet timestep="{i:d}" part="0" file="{rel}"/>' for i, rel in enumerate(entries)
    ]
    pvd_lines += ["  </Collection>", "</VTKFile>", ""]
    (pv_dir / "eigenmodes.pvd").write_text("\n".join(pvd_lines), encoding="utf-8")

    spec = _monitor_geometry(node_x, node_y, node_z)
    spec.update(
        {
            "name": "eigenmodes",
            "kind": "eigenmode",
            "data": "paraview/eigenmodes.pvd",
            "reader": "pvd",
            "glyph": None,
            "field_arrays": [*comps, "E", "H"],
        }
    )
    sl = _spatial_stride(cell_fields[0]["Ex"].shape)

    def steps():
        for i in _sample_steps(len(cell_fields)):
            yield [cell_fields[i][f"E{ax}"][sl] for ax in "xyz"]

    cap, exponent = _magnitude_stats(steps(), percentile)
    if cap > 0.0:
        # E only: the modes are peak-normalised per field, so an H glyph
        # set would be drawn at the same lengths from an unrelated
        # scaling — visually equal, physically incomparable.
        spec["glyph"] = {
            "arrays": ["E"],
            "cap": cap,
            "exponent": exponent,
            "length": spec["l_ref"],
            "threshold": cap * _VOLUME_THRESHOLD_FRACTION,
        }
    return spec


# ═════════════════════════════════════════════════════════════════════
# Session generation: paraview_open.py + baked paraview.pvsm
# ═════════════════════════════════════════════════════════════════════

_SCRIPT_HEADER = """\
# Generated by magnelio (DD-115) — ready-to-open ParaView session for this run.
#
#   Open in the GUI:   paraview --script=paraview_open.py
#   Bake a state file: pvpython paraview_open.py --save-state paraview.pvsm
#
# Regenerated by Project.export_paraview(); manual edits will be lost.
import json
import os
import sys

"""

_SCRIPT_BODY = """

def _abspath(rel):
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, rel))


def build():
    from paraview import servermanager, simple

    try:
        simple._DisableFirstRenderCameraReset()
    except Exception:
        pass
    view = simple.GetActiveViewOrCreate("RenderView")

    normals = {"x": [1.0, 0.0, 0.0], "y": [0.0, 1.0, 0.0], "z": [0.0, 0.0, 1.0]}

    def link_planes(name, a, b):
        # Two-way link between a slice plane and a geometry-clip plane so
        # dragging one drags the other.  Registered links survive into
        # saved state files.  Best-effort: purely cosmetic.
        try:
            link = servermanager.vtkSMProxyLink()
            link.AddLinkedProxy(a.SMProxy, 1)
            link.AddLinkedProxy(b.SMProxy, 2)
            link.AddLinkedProxy(b.SMProxy, 1)
            link.AddLinkedProxy(a.SMProxy, 2)
            servermanager.ProxyManager().RegisterLink(name, link)
        except Exception:
            pass

    unmirrored = []
    array_types = {10: "Float", 11: "Double"}

    def cell_array_types(source):
        # Element types of the cell arrays, by name.  The corrected copy
        # has to keep the precision of the original: a double array
        # meeting its float twin where the halves are joined makes the
        # array vanish from the joined dataset without a word — and that
        # array is the one carrying the field.  Reading the type off the
        # data cannot guess wrong, which is why it is worth the one
        # pipeline pass it costs.
        out = {}
        try:
            source.UpdatePipeline()
            info = source.GetDataInformation().GetCellDataInformation()
            for i in range(info.GetNumberOfArrays()):
                a = info.GetArrayInformation(i)
                out[a.GetName()] = array_types.get(a.GetDataType(), "Double")
        except Exception:
            pass
        return out

    def mirror_plane(r, axis, wall):
        # Place a reflection filter on an arbitrary axis-aligned plane.
        # ParaView 6 renamed every property involved and dropped the free
        # axis entry from the mode list, so an arbitrary plane now goes
        # through a plane sub-proxy; older builds keep the flat
        # Plane/Center pair.  Returns False when neither shape fits, and
        # the caller must then not pretend a half model is a whole one.
        props = r.ListProperties()
        origin = [0.0, 0.0, 0.0]
        origin["xyz".index(axis)] = wall
        try:
            if "PlaneMode" in props:
                r.PlaneMode = "Interactive"
                r.ReflectionPlane.Origin = origin
                r.ReflectionPlane.Normal = normals[axis]
            else:
                r.Plane = axis.upper()
                r.Center = wall
        except Exception:
            return False
        # Without this the filter continues only arrays flagged as
        # vectors, and the sign corrections below assume it ran.
        for flag in ("ReflectAllInputArrays", "FlipAllInputArrays"):
            if flag in props:
                try:
                    setattr(r, flag, 1)
                    return True
                except Exception:
                    pass
        return False

    def reflected(inp, label, fixes=None, clip_first=False, merge=False):
        # Symmetry planes: half-model data on disk, full model in the
        # renderer — one reflection per declared plane.  clip_first drops
        # the far half of a fully modelled geometry so only the simulated
        # half is mirrored (the display shows what the solver saw).
        #
        # The filter continues every 3-component array as a polar vector.
        # That is the exact continuation for one pairing of field and
        # wall type only; *fixes* lists, per plane, the arrays left with
        # the wrong sign — including the single components, which the
        # filter does not touch at all.  Those planes reflect without the
        # input copy, so the mirrored branch stands alone and its
        # correction is a constant factor needing no coordinate test,
        # and the two halves are rejoined afterwards.
        #
        # *merge* flattens the dataset around every reflection, and field
        # data needs it twice over.  Reflecting a composite dataset
        # assigns the continued vector to different cells than the
        # untouched single components, so colour and arrows would come
        # from different places; and joining two halves leaves cell-to-
        # point averaging blind to the seam, which puts a non-zero
        # tangential field on an electric wall.  Geometry has neither
        # problem and keeps its blocks, which carry the body names.
        head = inp
        grouped = False
        for i, plane in enumerate(CONFIG.get("symmetry") or []):
            axis, wall, at_low = plane[0], plane[1], plane[2]
            before, built = head, []
            if clip_first:
                cl = simple.Clip(
                    registrationName="%s_symclip_%d" % (label, i), Input=head
                )
                cl.ClipType = "Plane"
                origin = [0.0, 0.0, 0.0]
                origin["xyz".index(axis)] = wall
                cl.ClipType.Origin = origin
                cl.ClipType.Normal = normals[axis]
                cl.Invert = 0 if at_low else 1
                head = cl
                built.append(cl)
            if merge:
                head = simple.MergeBlocks(
                    registrationName="%s_flat_%d" % (label, i), Input=head
                )
                built.append(head)
            r = simple.Reflect(
                registrationName="%s_mirror_%d" % (label, i), Input=head
            )
            built.append(r)
            if not mirror_plane(r, axis, wall):
                # Half-built filters left hanging in the pipeline are
                # exactly what makes this failure read as a feature.
                for proxy in reversed(built):
                    simple.Delete(proxy)
                unmirrored.append(label)
                return before
            fix = fixes[i] if fixes and i < len(fixes) else []
            if not fix:
                r.CopyInput = 1
                head, grouped = r, False
                continue
            r.CopyInput = 0
            types = cell_array_types(r)
            branch = r
            for name, factor in fix:
                calc = simple.Calculator(
                    registrationName="%s_sign_%d_%s" % (label, i, name), Input=branch
                )
                calc.AttributeType = "Cell Data"
                calc.ResultArrayName = name
                calc.Function = '%g*"%s"' % (factor, name)
                try:
                    calc.ResultArrayType = types.get(name, "Double")
                except Exception:
                    pass
                branch = calc
            head = simple.GroupDatasets(
                registrationName="%s_joined_%d" % (label, i), Input=[head, branch]
            )
            grouped = True
        if merge and grouped:
            head = simple.MergeBlocks(registrationName="%s_full" % label, Input=head)
        return head

    # -- geometry: coloured per material via categorical LUT -----------
    geom = None
    if CONFIG.get("geometry") and os.path.exists(_abspath(CONFIG["geometry"])):
        geom = simple.XMLMultiBlockDataReader(
            registrationName="geometry", FileName=[_abspath(CONFIG["geometry"])]
        )
        geom = reflected(geom, "geometry", clip_first=True)
        disp = simple.Show(geom, view)
        disp.Representation = "Surface"
        simple.ColorBy(disp, ("CELLS", "MaterialIndex"))
        lut = simple.GetColorTransferFunction("MaterialIndex")
        lut.InterpretValuesAsCategories = 1
        annotations, colors, opacities = [], [], []
        for i, mat in enumerate(CONFIG["materials"]):
            annotations += [str(i), mat["name"]]
            colors += [float(c) for c in mat["rgba"][:3]]
            opacities.append(float(mat["rgba"][3]))
        lut.Annotations = annotations
        lut.IndexedColors = colors
        try:
            lut.IndexedOpacities = opacities
            lut.EnableOpacityMapping = 1
        except Exception:
            pass
        disp.Opacity = 0.85

    # -- monitors ------------------------------------------------------
    shown_any = False
    for mon in CONFIG["monitors"]:
        path = _abspath(mon["data"])
        if not os.path.exists(path):
            continue
        if mon["reader"] == "xdmf":
            src = simple.XDMFReader(registrationName=mon["name"], FileNames=[path])
        else:
            src = simple.PVDReader(registrationName=mon["name"], FileName=path)
        src = reflected(src, mon["name"], mon.get("mirror_fix"), merge=True)
        pts = simple.CellDatatoPointData(registrationName=mon["name"] + "_points", Input=src)

        glyph = mon.get("glyph")
        arrays = glyph["arrays"] if glyph else []

        def lattice(label, dims):
            # Everything downstream is glyphed on an evenly spaced lattice.
            # The computational grid is deliberately NOT used for arrow
            # placement: its spacing routinely varies by a factor of 40
            # between a geometry-refined region and a wavelength-sized one,
            # which reads as arrows crowding into isolated planes with
            # voids between them.  Resampling happens on the RAW field,
            # ahead of the direction calculators below, so the non-linear
            # length map is applied to interpolated field values rather
            # than the interpolation being applied to compressed ones.
            r = simple.ResampleToImage(registrationName=label, Input=pts)
            r.SamplingDimensions = dims
            return r

        def direction_arrays(inp, prefix):
            # One direction array per field array.  The Calculator maps the
            # magnitude to a DIMENSIONLESS 0..1 length factor, so the glyph
            # ScaleFactor below is a plain length in metres — the length of
            # the longest arrow, readable and inside the range ParaView's
            # slider offers.
            #
            #   |dir| = (min(|v|, cap) / cap) ^ exponent
            #
            # Two baked numbers do two separate jobs: `cap` saturates the
            # edge singularities, and `exponent` < 1 compresses the length
            # span so the typical field-carrying magnitude still shows.  A
            # linear map (exponent 1) cannot: a whole-domain monitor is
            # routinely half zeros (PEC interior, quiet volume), which puts
            # the typical magnitude 20-30x below the cap and its arrow
            # below a millimetre.  The exponent is fitted per monitor at
            # export time, so a more extreme distribution compresses harder.
            head = inp
            for arr in arrays:
                mag = simple.Calculator(
                    registrationName="%s_%s_mag" % (prefix, arr), Input=head
                )
                mag.AttributeType = "Point Data"
                mag.ResultArrayName = arr + "_mag"
                mag.Function = "mag(%s)" % arr
                calc = simple.Calculator(
                    registrationName="%s_%s_dir" % (prefix, arr), Input=mag
                )
                calc.AttributeType = "Point Data"
                calc.ResultArrayName = arr + "_dir"
                eps = glyph["cap"] * 1e-12
                calc.Function = "%s*((min(mag(%s),%.9g)/%.9g)^%.6g)/(mag(%s)+%.9g)" % (
                    arr,
                    arr,
                    glyph["cap"],
                    glyph["cap"],
                    glyph["exponent"],
                    arr,
                    eps,
                )
                head = calc
            return head

        def make_glyph(inp, label, arr):
            gly = simple.Glyph(registrationName=label, Input=inp, GlyphType="Arrow")
            gly.OrientationArray = ["POINTS", arr + "_dir"]
            gly.ScaleArray = ["POINTS", arr + "_dir"]
            gly.VectorScaleMode = "Scale by Magnitude"
            gly.ScaleFactor = glyph["length"]
            # The input already IS the even spacing asked for, so every
            # point carries an arrow; any seeding mode would undo it.
            gly.GlyphMode = "All Points"
            return gly

        def field_region(inp, label, arr):
            # Cells carrying field, for the volume glyphs; *inp* unchanged
            # when this ParaView predates the current Threshold API.
            try:
                thr = simple.Threshold(registrationName=label, Input=inp)
                thr.Scalars = ["POINTS", arr + "_mag"]
                thr.LowerThreshold = glyph["threshold"]
                thr.UpperThreshold = 1e30
                return thr
            except Exception:
                return inp  # older Threshold API: glyph the whole volume

        def show_coloured(proxy, arr=None):
            d = simple.Show(proxy, view)
            if arr:
                # Colour carries the TRUE magnitude (linear, un-compressed);
                # only the arrow length is compressed.
                simple.ColorBy(d, ("POINTS", arr, "Magnitude"))
                lut = simple.GetColorTransferFunction(arr)
                lut.RescaleTransferFunction(0.0, glyph["cap"])
                try:
                    lut.AutomaticRescaleRangeMode = "Never"
                except Exception:
                    pass
                d.SetScalarBarVisibility(view, True)
            return d

        is_first = not shown_any
        dims = mon.get("resample_dims")
        if not arrays or not dims:
            continue
        head = direction_arrays(lattice(mon["name"] + "_lattice", dims), mon["name"])

        if mon["slice_axes"]:
            # Whole-volume arrows get their own, coarser lattice: the one
            # feeding the cuts is sized for in-plane density, and glyphing
            # every one of its points in 3D would bury the field under its
            # own arrows.
            vol_dims = mon.get("resample_dims_volume")
            if vol_dims:
                vol = direction_arrays(
                    lattice(mon["name"] + "_lattice_volume", vol_dims),
                    mon["name"] + "_volume",
                )
                for arr in arrays:
                    region = field_region(
                        vol, "%s_volume_region_%s" % (mon["name"], arr), arr
                    )
                    make_glyph(region, "%s_volume_%s" % (mon["name"], arr), arr)
            for axis in mon["slice_axes"]:
                sl = simple.Slice(
                    registrationName="%s_slice_%s" % (mon["name"], axis), Input=head
                )
                sl.SliceType = "Plane"
                sl.SliceType.Origin = mon["center"]
                sl.SliceType.Normal = normals[axis]
                glyphs = [
                    (arr, make_glyph(sl, "%s_arrows_%s_%s" % (mon["name"], arr, axis), arr))
                    for arr in arrays
                ]
                if geom is not None:
                    clip = simple.Clip(
                        registrationName="geometry_cut_%s_%s" % (mon["name"], axis),
                        Input=geom,
                    )
                    clip.ClipType = "Plane"
                    clip.ClipType.Origin = mon["center"]
                    clip.ClipType.Normal = normals[axis]
                    link_planes("plane_%s_%s" % (mon["name"], axis), sl.SliceType, clip.ClipType)
                if is_first and axis == mon["default_axis"]:
                    show_coloured(sl)
                    # Only the first array's arrows are shown; the others
                    # (the imaginary part of a frequency monitor) sit
                    # ready in the pipeline, one click from visible.
                    for arr, gly in glyphs[:1]:
                        show_coloured(gly, arr)
                    shown_any = True
        else:
            # Planar (or lower-dimensional) monitor: the lattice already is
            # the section — glyph it directly, no slicing needed.
            glyphs = [
                (arr, make_glyph(head, "%s_arrows_%s" % (mon["name"], arr), arr)) for arr in arrays
            ]
            if geom is not None and mon.get("planar_normal"):
                clip = simple.Clip(registrationName="geometry_cut_" + mon["name"], Input=geom)
                clip.ClipType = "Plane"
                clip.ClipType.Origin = mon["center"]
                clip.ClipType.Normal = normals[mon["planar_normal"]]
            if is_first:
                show_coloured(head)
                for arr, gly in glyphs[:1]:
                    show_coloured(gly, arr)
                shown_any = True

    if unmirrored:
        # Announced in the view itself, not only on stdout: the failure
        # shows a half model that looks like a whole one, and nothing
        # else in the picture says so.
        print(SYMMETRY_MARKER + " " + ",".join(sorted(set(unmirrored))))
        try:
            note = simple.Text(registrationName="symmetry_note")
            note.Text = (
                "Symmetry mirroring is not available in this ParaView build.\\n"
                "Showing the simulated part of the model only."
            )
            simple.Show(note, view).Color = [1.0, 0.35, 0.25]
        except Exception:
            pass

    try:
        simple.GetAnimationScene().UpdateAnimationUsingDataTimeSteps()
    except Exception:
        pass
    simple.ResetCamera(view)
    try:
        simple.Render(view)
    except Exception:
        pass


build()
argv = sys.argv[1:]
if "--save-state" in argv:
    from paraview.simple import SaveState

    SaveState(os.path.abspath(argv[argv.index("--save-state") + 1]))
"""


def write_paraview_script(script_path: str | Path, config: dict) -> Path:
    """Write the generated ``paraview.simple`` pipeline script."""
    script_path = Path(script_path)
    payload = json.dumps(config)
    script_path.write_text(
        _SCRIPT_HEADER
        + f"CONFIG = json.loads({payload!r})\n"
        + f"SYMMETRY_MARKER = {_SYMMETRY_MARKER!r}\n"
        + _SCRIPT_BODY,
        encoding="utf-8",
    )
    return script_path


def bake_pvsm(script_path: str | Path, pvsm_path: str | Path, timeout: float = 300.0) -> bool:
    """Bake the pipeline script into a ``.pvsm`` state file via ``pvpython``.

    Returns ``False`` (without raising) when ``pvpython`` is missing or
    the bake fails — the script remains the portable fallback.
    ``MAGNELIO_PVSM_BAKE=0`` disables the bake globally (the test suite
    pins this: a ``pvpython`` subprocess per streamed run would dominate
    its runtime).
    """
    import os  # noqa: PLC0415

    if os.environ.get("MAGNELIO_PVSM_BAKE", "1") == "0":
        return False
    exe = shutil.which("pvpython")
    if exe is None:
        return False
    pvsm_path = Path(pvsm_path)
    cmd = [
        exe,
        "--force-offscreen-rendering",
        str(script_path),
        "--save-state",
        str(pvsm_path),
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, check=False)
    except (OSError, subprocess.TimeoutExpired):
        return False
    if _SYMMETRY_MARKER in (proc.stdout or ""):
        warnings.warn(
            "ParaView could not place the symmetry mirror planes, so the session "
            "shows only the simulated part of the model. The reflection filter of "
            "this ParaView build exposes none of the property sets magnelio knows.",
            RuntimeWarning,
            stacklevel=2,
        )
    return proc.returncode == 0 and pvsm_path.exists()


def _geometry_config(project_path: Path, rel: str) -> tuple[str | None, list[dict]]:
    """``(relative geometry.vtm path, material table)`` for a session.

    *rel* is the path from the session script's own directory, which
    differs between a run session (two levels down) and the project-level
    eigenmode session (alongside).
    """
    from magnelio.io.project import _material_from_dict  # noqa: PLC0415

    if not (project_path / "geometry.vtm").exists():
        return None, []
    gj_path = project_path / "geometry.json"
    if not gj_path.exists():
        return rel, []
    gj = json.loads(gj_path.read_text(encoding="utf-8"))
    kinds = gj.get("kinds", ["solid"] * len(gj["materials"]))
    file_colors = gj.get("colors") or [None] * len(gj["materials"])
    pairs = [
        (_material_from_dict(d), c)
        for d, c, kind in zip(gj["materials"], file_colors, kinds)
        if kind != "wire"
    ]
    materials, _ = _material_table([m for m, _ in pairs], [c for _, c in pairs])
    return rel, materials


def _symmetry_config(project) -> list:
    """Declared symmetry planes as ``[[axis, wall_m, at_low, kind], ...]``.

    Read from the stored mesh (DD-154); the wall coordinate reuses the
    monitor mirror resolution (PEC on the outermost grid line, PMC half
    the boundary cell outside — the physical mirror plane).  The wall
    *kind* travels with it because it decides the sign every field
    component picks up across the plane.  Empty when the project stores
    no mesh or the mesh declares no symmetry.
    """
    from magnelio.monitors.base import resolve_mirrors, resolve_region  # noqa: PLC0415

    try:
        mesh = project.mesh
    except Exception:  # noqa: BLE001 — no stored mesh
        return []
    if mesh is None:
        return []
    mirrors = resolve_mirrors(resolve_region(None, mesh.grid), mesh)
    return [["xyz"[m.axis], m.wall, m.at_low, m.kind] for m in mirrors]


def export_eigenmode_visualization(
    project_path: str | Path,
    *,
    glyph_percentile: float = 98.0,
    bake_state: bool = True,
) -> dict:
    """Generate the ready-to-open ParaView session for stored eigenmodes.

    The eigenmode counterpart of :func:`export_run_visualization`.
    Eigenmodes belong to the project rather than to a run (they have no
    excitation and no time axis), so the artefacts sit in the project
    directory itself: ``paraview/eigenmodes/mode_*.vtr`` plus
    ``paraview/eigenmodes.pvd``, the pipeline script
    ``paraview_open.py`` and — when *bake_state* and ``pvpython`` is
    available — ``paraview.pvsm``.

    Stepping the ParaView time axis steps through the **modes**; each
    file carries its eigenfrequency as field data.  Fields are
    peak-normalised per mode (an eigenvector has no absolute
    amplitude), with the divisors stored alongside.

    Parameters
    ----------
    project_path : str or Path
        The project directory; must contain ``eigenmodes.h5``.
    glyph_percentile : float, default 98.0
        Percentile of ``|E|`` used as the glyph magnitude clip cap.
    bake_state : bool, default True
        Attempt the ``pvpython`` state bake.

    Returns
    -------
    dict
        Written artefact paths (``script``, ``state`` or ``None``,
        ``monitors``); empty when the project stores no eigenmodes.
    """
    from magnelio.io.project import Project  # noqa: PLC0415

    project = Project(project_path)
    if not (project.path / "eigenmodes.h5").exists():
        return {}

    pv_dir = project.path / "paraview"
    pv_dir.mkdir(exist_ok=True)
    spec = _export_eigenmodes(project.path, pv_dir, project.grid, glyph_percentile)
    if spec is None:
        return {}

    geometry_rel, materials = _geometry_config(project.path, "geometry.vtm")
    mirrors = _symmetry_config(project)
    _prepare_mirroring([spec], mirrors)
    config = {
        "geometry": geometry_rel,
        "materials": materials,
        "monitors": [spec],
        "symmetry": mirrors,
    }
    script = write_paraview_script(project.path / "paraview_open.py", config)
    state = project.path / "paraview.pvsm"
    baked = bake_state and bake_pvsm(script, state)
    return {
        "script": script,
        "state": state if baked else None,
        "monitors": ["eigenmodes"],
    }


def export_run_visualization(
    project_path: str | Path,
    run_name: str,
    *,
    glyph_percentile: float = 98.0,
    bake_state: bool = True,
) -> dict:
    """Generate the ready-to-open ParaView session for one stored run.

    Writes, under ``runs/<run_name>/``:

    * ``paraview/<monitor>.xdmf`` — one descriptor per field-time monitor
      (referencing ``results.h5``, no data duplication),
    * ``paraview/<monitor>.pvd`` + ``paraview/<monitor>/f_*.vtr`` — the
      frequency-monitor DFT as a frequency series,
    * ``paraview_open.py`` — the ``paraview.simple`` pipeline script,
    * ``paraview.pvsm`` — a double-clickable state file, when *bake_state*
      and ``pvpython`` is available.

    Parameters
    ----------
    project_path : str or Path
        The project directory.
    run_name : str
        Run subdirectory name under ``runs/``.
    glyph_percentile : float, default 98.0
        Percentile of ``|v|`` used as the glyph magnitude clip cap.
    bake_state : bool, default True
        Attempt the ``pvpython`` state bake.

    Returns
    -------
    dict
        Paths of the written artefacts (``script``, ``state`` or
        ``None``, ``monitors`` list); empty when there is nothing to
        visualise.
    """
    from magnelio.io.project import (  # noqa: PLC0415
        Project,
        _list_run_freq,
        _list_run_monitors,
    )

    project = Project(project_path)
    run_dir = project.path / "runs" / run_name
    if not run_dir.is_dir():
        raise FileNotFoundError(f"no such run directory: {run_dir}")

    geometry_rel, materials = _geometry_config(project.path, "../../geometry.vtm")

    pv_dir = run_dir / "paraview"
    pv_dir.mkdir(exist_ok=True)

    monitors = []
    for name in _list_run_monitors(run_dir):
        spec = _export_time_monitor(run_dir, pv_dir, name, glyph_percentile)
        if spec is not None:
            monitors.append(spec)
    freq_names = _list_run_freq(run_dir)
    if freq_names:
        grid = project.grid
        for name in freq_names:
            spec = _export_freq_monitor(run_dir, pv_dir, name, grid, glyph_percentile)
            if spec is not None:
                monitors.append(spec)

    if not monitors and geometry_rel is None:
        return {}

    mirrors = _symmetry_config(project)
    _prepare_mirroring(monitors, mirrors)
    config = {
        "geometry": geometry_rel,
        "materials": materials,
        "monitors": monitors,
        "symmetry": mirrors,
    }
    script = write_paraview_script(run_dir / "paraview_open.py", config)
    state = run_dir / "paraview.pvsm"
    baked = bake_state and bake_pvsm(script, state)
    return {
        "script": script,
        "state": state if baked else None,
        "monitors": [m["name"] for m in monitors],
    }
