"""ParaView export: multiblock geometry, frequency grids, session state.

Three layers:

1. :func:`export_vtm` — tessellate each solid into its own block of a VTK
   multiblock dataset (``geometry.vtm`` + ``geometry/*.vtp``).  Blocks carry
   the shape name and a ``MaterialIndex`` cell array; a categorical lookup
   table colours the blocks per material (colours from
   :func:`~magnelio.post._colors.material_color`, the same palette as the
   built-in 3D viewer).
2. Frequency-monitor export — the ``fields_freq.h5`` DFT bins as one
   rectilinear ``.vtr`` file per frequency plus a ``.pvd`` collection
   (frequency plays the role of the ParaView time axis).  Time monitors
   are written the same way, one ``.vtr`` per frame, converted from the
   staggered frames the store holds (DD-259).
   Eigenmodes take the same ``.vtr``/``.pvd`` shape one directory up
   (they belong to the project, not to a run), with the *mode index*
   on the ParaView axis — see :func:`export_eigenmode_visualization`.
3. :func:`export_run_visualization` — generates ``paraview_open.py``, a
   ``paraview.simple`` pipeline script (coloured geometry, one Python
   filter per monitor that mirrors, averages and resamples the field
   onto an even lattice, a cut with magnitude-clipped arrows, the
   geometry clip linked to the cut plane) and, when ``pvpython`` is on
   the PATH, bakes it into a double-clickable ``paraview.pvsm`` file.

Everything here is written on request — by :meth:`Project.export_paraview`
and :meth:`Project.export_paraview_eigenmodes`, never at a run's close
(DD-262).  The geometry tessellation is best-effort; a failure there
warns and the field export goes on without the solids.
"""

# Design: DD-115 (three-layer ParaView export pipeline), DD-262 (export on
# request, one ProgrammableFilter per monitor).

from __future__ import annotations

import json
import re
import shutil
import subprocess
import warnings
from pathlib import Path

import numpy as np

# Glyphs are sized so a full-length arrow spans this fraction of the
# monitor's bounding-box diagonal.
_GLYPH_LENGTH_FRACTION = 1.0 / 25.0
# Spatial samples used when estimating the magnitude statistics.
_CAP_MAX_SAMPLES = 1_500_000
_CAP_TIME_SAMPLES = 6
# Cells below this fraction of the peak magnitude do not count towards the
# length reference (PEC interiors, quiet volume).
_LIVE_CELL_FRACTION = 0.01
# Percentile of the field-carrying cells taken as the typical magnitude.
_REFERENCE_PERCENTILE = 60.0
# ... which is drawn at this fraction of the full arrow length.  Fixing
# the pair (reference -> this fraction, cap -> full length) is what the
# glyph length exponent is fitted to.
_REFERENCE_LENGTH_FRACTION = 0.45
_EXPONENT_LIMITS = (0.2, 1.0)
# Volume glyphs drop cells below this fraction of the cap: a whole-domain
# monitor is mostly PEC interior and quiet volume, and filling those with
# short arrows buries the field.  Slice glyphs keep every cell — on a
# single cut the empty regions read as information, not clutter.
_VOLUME_THRESHOLD_FRACTION = 0.02
# Arrows are always placed on an evenly spaced lattice (DD-115 follow-up),
# never on the computational grid.  Two lattices per 3D monitor, because
# the two views need different densities: a cut wants arrows per unit
# AREA, a volume view a bounded total count.
_ARROWS_PER_SECTION = 2000
_RESAMPLE_VOLUME_POINTS = 8000
_RESAMPLE_MAX_PER_AXIS = 300

#: Component axis behind a field-array suffix (``Ey`` -> 1).
_COMP_AXES = {"x": 0, "y": 1, "z": 2}

#: Printed by the session script after it saves a state file, and read
#: back by :func:`bake_pvsm`: a ``.pvsm`` is bound to the ParaView that
#: wrote it (proxy names change between releases), so the version goes
#: into the script's header where a later reader can find it.
_VERSION_MARKER = "MAGNELIO_PARAVIEW_VERSION"


def _sanitize(name: str) -> str:
    """File-system-safe token for a monitor / block name."""
    return re.sub(r"[^\w.-]+", "_", name).strip("_") or "unnamed"


def _material_table(materials, colors=None) -> tuple[list[dict], list[int]]:
    """Unique material table and the per-shape index into it.

    Deterministic for a given shape order, so the ``MaterialIndex`` cell
    array written by :func:`export_vtm` and the lookup table generated by
    :func:`export_run_visualization` (which re-derives the table from
    ``geometry.json``) always agree.

    *colors* optionally carries the per-shape display colour imported
    from a CAD file, so two shapes of the same material but different
    file colours become two entries.
    """
    from magnelio.post._colors import material_color  # noqa: PLC0415

    table: list[dict] = []
    index_of: dict = {}
    used_names: set[str] = set()
    indices = []
    if colors is None:
        colors = [None] * len(materials)
    for mat, color in zip(materials, colors):
        rgba = tuple(round(float(c), 6) for c in material_color(mat, color))
        if rgba[3] == 0.0 and getattr(mat, "color", None) is None and getattr(mat, "visible", True):
            # Auto-coloured air/vacuum: the 2D cross-sections draw it as
            # a dashed wall outline, but in 3D the vacuum volume IS the
            # device (a cavity carved into metal) — render it as a light
            # translucent blue instead of not at all.  An explicit
            # Material(color=..., alpha=...) or visible=False still wins.
            rgba = (0.25, 0.5, 1.0, 0.3)
        name = getattr(mat, "name", None) or "material"
        key = (name, rgba)
        if key not in index_of:
            label = name
            n = 2
            while label in used_names:
                label = f"{name} #{n}"
                n += 1
            used_names.add(label)
            index_of[key] = len(table)
            table.append({"name": label, "rgba": list(rgba)})
        indices.append(index_of[key])
    return table, indices


# ═════════════════════════════════════════════════════════════════════
# Geometry: per-solid tessellation -> multiblock .vtm
# ═════════════════════════════════════════════════════════════════════


# OCC rejects a linear deflection below ``Precision::Confusion()`` (1e-7
# in the kernel's units) with a Standard_NumericError; a body of a few
# tens of micrometres at metre scale asks for less, so every deflection
# handed to ``BRepMesh_IncrementalMesh`` is floored here.
_OCC_MIN_DEFLECTION = 1.1e-7


def _occ_deflection(shape, rel: float) -> float:
    """Linear deflection as a fraction of the shape's bbox diagonal."""
    from OCC.Core.Bnd import Bnd_Box  # noqa: PLC0415

    try:
        from OCC.Core.BRepBndLib import brepbndlib  # noqa: PLC0415

        add = brepbndlib.Add
    except ImportError:  # pragma: no cover - legacy pythonocc naming
        from OCC.Core.BRepBndLib import brepbndlib_Add as add  # noqa: PLC0415

    box = Bnd_Box()
    add(shape, box)
    if box.IsVoid():
        return 1e-4
    xmin, ymin, zmin, xmax, ymax, zmax = box.Get()
    diag = float(np.sqrt((xmax - xmin) ** 2 + (ymax - ymin) ** 2 + (zmax - zmin) ** 2))
    return max(rel * diag, _OCC_MIN_DEFLECTION)


def _tessellate_shape(occ_shape, deflection: float | None, angular_deflection: float = 0.5):
    """Triangulate one TopoDS shape into ``(points, triangles)`` arrays.

    Returns ``None`` when the shape yields no triangulation (e.g. an
    empty compound).  Face orientation is honoured so outward normals
    survive into the ``.vtp`` blocks.  ``angular_deflection`` [rad]
    bounds the angle between neighbouring facets on curved faces (the
    OCC default 0.5 leaves visible facets on cylinders).
    """
    from OCC.Core.BRep import BRep_Tool  # noqa: PLC0415
    from OCC.Core.BRepMesh import BRepMesh_IncrementalMesh  # noqa: PLC0415
    from OCC.Core.TopAbs import TopAbs_FACE, TopAbs_REVERSED  # noqa: PLC0415
    from OCC.Core.TopExp import TopExp_Explorer  # noqa: PLC0415
    from OCC.Core.TopLoc import TopLoc_Location  # noqa: PLC0415
    from OCC.Core.TopoDS import topods  # noqa: PLC0415

    defl = deflection if deflection is not None else _occ_deflection(occ_shape, 2e-3)
    defl = max(float(defl), _OCC_MIN_DEFLECTION)
    BRepMesh_IncrementalMesh(occ_shape, defl, False, angular_deflection, True)

    points: list[np.ndarray] = []
    tris: list[np.ndarray] = []
    offset = 0
    exp = TopExp_Explorer(occ_shape, TopAbs_FACE)
    while exp.More():
        face = topods.Face(exp.Current())
        exp.Next()
        loc = TopLoc_Location()
        tri = BRep_Tool.Triangulation(face, loc)
        if tri is None:
            continue
        trsf = loc.Transformation()
        n_nodes = tri.NbNodes()
        pts = np.empty((n_nodes, 3), dtype=np.float64)
        for i in range(1, n_nodes + 1):
            p = tri.Node(i).Transformed(trsf)
            pts[i - 1] = (p.X(), p.Y(), p.Z())
        n_tri = tri.NbTriangles()
        con = np.empty((n_tri, 3), dtype=np.int64)
        reversed_face = face.Orientation() == TopAbs_REVERSED
        for i in range(1, n_tri + 1):
            a, b, c = tri.Triangle(i).Get()
            con[i - 1] = (c, b, a) if reversed_face else (a, b, c)
        points.append(pts)
        tris.append(con - 1 + offset)
        offset += n_nodes
    if not points:
        return None
    return np.vstack(points), np.vstack(tris)


def _polydata(points: np.ndarray, triangles: np.ndarray):
    """Build a ``vtkPolyData`` from point / triangle index arrays."""
    import vtk  # noqa: PLC0415
    from vtk.util import numpy_support as ns  # noqa: PLC0415

    pd = vtk.vtkPolyData()
    vpts = vtk.vtkPoints()
    vpts.SetData(ns.numpy_to_vtk(np.ascontiguousarray(points), deep=True))
    pd.SetPoints(vpts)
    n_tri = triangles.shape[0]
    offsets = np.arange(0, 3 * (n_tri + 1), 3, dtype=np.int64)
    conn = np.ascontiguousarray(triangles, dtype=np.int64).ravel()
    ca = vtk.vtkCellArray()
    ca.SetData(
        ns.numpy_to_vtkIdTypeArray(offsets, deep=True),
        ns.numpy_to_vtkIdTypeArray(conn, deep=True),
    )
    pd.SetPolys(ca)
    return pd


def _half_and_mirror(pd, axis: int, wall: float, at_low: bool):
    """Clip *pd* to the simulated half and append its reflection (DD-265).

    The solids of a model behind symmetry planes are stored as the half
    the solver saw; ParaView used to complete them with its own
    ``Reflect`` filter, whose proxy name changed between releases and
    took the whole geometry branch of a baked state down with it.  The
    completion happens here instead, in this process's VTK, so the
    session only ever reads a whole model.

    A mirror reverses the winding of every triangle, so the reflected
    copy is passed through ``vtkReverseSense``; without it the solids
    would be lit from inside.
    """
    import vtk  # noqa: PLC0415

    origin = [0.0, 0.0, 0.0]
    origin[axis] = wall
    normal = [0.0, 0.0, 0.0]
    normal[axis] = 1.0
    plane = vtk.vtkPlane()
    plane.SetOrigin(origin)
    plane.SetNormal(normal)

    clip = vtk.vtkClipPolyData()
    clip.SetInputData(pd)
    clip.SetClipFunction(plane)
    # The wall at the low end leaves the model on the positive side.
    clip.SetInsideOut(0 if at_low else 1)
    clip.Update()
    half = clip.GetOutput()
    if half.GetNumberOfCells() == 0:
        return pd

    transform = vtk.vtkTransform()
    shift = [0.0, 0.0, 0.0]
    shift[axis] = 2.0 * wall
    scale = [1.0, 1.0, 1.0]
    scale[axis] = -1.0
    # Pre-multiplied: the scale acts first, so x -> 2*wall - x.
    transform.Translate(*shift)
    transform.Scale(*scale)
    mirrored = vtk.vtkTransformPolyDataFilter()
    mirrored.SetInputData(half)
    mirrored.SetTransform(transform)
    flip = vtk.vtkReverseSense()
    flip.SetInputConnection(mirrored.GetOutputPort())
    flip.ReverseCellsOn()
    flip.ReverseNormalsOn()

    append = vtk.vtkAppendPolyData()
    append.AddInputData(half)
    append.AddInputConnection(flip.GetOutputPort())
    append.Update()
    return append.GetOutput()


def export_vtm(
    path: str | Path,
    geometry,
    deflection: float | None = None,
    mirrors=None,
) -> list[dict]:
    """Export solids as a per-solid VTK multiblock dataset (``.vtm``).

    Each solid becomes its own named block carrying a constant
    ``MaterialIndex`` cell array (index into the returned material table)
    and the material name as field data, so ParaView can colour blocks
    per material with a categorical lookup table and users can hide or
    extract individual solids.

    Parameters
    ----------
    path : str or Path
        Output file path (``.vtm``; a sibling data directory is created).
    geometry : iterable
        Shape objects exposing ``_occ_shape()`` and ``material`` —
        a :class:`~magnelio.geo.GeometryModel`, a
        :class:`~magnelio.io.project.LoadedGeometry`, or a plain list.
        Thin wires must be filtered out by the caller.
    deflection : float, optional
        Absolute tessellation accuracy [m].  Default: 0.2 % of each
        solid's bounding-box diagonal (scale-independent).
    mirrors : sequence, optional
        Declared symmetry planes as ``(axis, wall [m], at_low, kind)``.
        Every block is clipped to the simulated half and completed
        across each plane, so the file holds the whole model.

    Returns
    -------
    list of dict
        The material table (``{"name", "rgba"}`` per entry) the block
        colouring refers to.
    """
    import vtk  # noqa: PLC0415
    from vtk.util import numpy_support as ns  # noqa: PLC0415

    shapes = list(geometry)
    table, indices = _material_table(
        [s.material for s in shapes], [getattr(s, "color", None) for s in shapes]
    )

    # DD-120: tessellate at the model scale, convert points to meters.
    geo_scale = 1.0
    if shapes and all(hasattr(s, "_analytic_bbox") for s in shapes):
        from magnelio.geo._scaling import model_scale  # noqa: PLC0415

        geo_scale = model_scale(shapes)

    mb = vtk.vtkMultiBlockDataSet()
    mb.SetNumberOfBlocks(len(shapes))
    used_names: set[str] = set()
    for i, shape in enumerate(shapes):
        name = getattr(shape, "name", None) or f"shape_{i}"
        label = name
        n = 2
        while label in used_names:
            label = f"{name}_{n}"
            n += 1
        used_names.add(label)
        mb.GetMetaData(i).Set(vtk.vtkCompositeDataSet.NAME(), label)

        tess = _tessellate_shape(
            shape._occ_shape(geo_scale),
            None if deflection is None else deflection * geo_scale,
        )
        if tess is None:
            continue
        tess_points, tess_tris = tess
        pd = _polydata(tess_points / geo_scale, tess_tris)
        mat_idx = np.full(pd.GetNumberOfCells(), indices[i], dtype=np.int32)
        arr = ns.numpy_to_vtk(mat_idx, deep=True)
        arr.SetName("MaterialIndex")
        pd.GetCellData().AddArray(arr)
        for plane in mirrors or ():
            axis = "xyz".index(plane[0])
            pd = _half_and_mirror(pd, axis, float(plane[1]), bool(plane[2]))
        name_arr = vtk.vtkStringArray()
        name_arr.SetName("MaterialName")
        name_arr.InsertNextValue(table[indices[i]]["name"])
        pd.GetFieldData().AddArray(name_arr)
        mb.SetBlock(i, pd)

    writer = vtk.vtkXMLMultiBlockDataWriter()
    writer.SetFileName(str(path))
    writer.SetInputData(mb)
    writer.Write()
    return table


# ═════════════════════════════════════════════════════════════════════
# Monitors: caps, per-monitor .vtr series over time and frequency
# ═════════════════════════════════════════════════════════════════════


def _pick_vector(components) -> tuple[str, list[str]] | None:
    """The preferred complete field triple among *components* (E over H)."""
    comps = set(components)
    for field in ("E", "H"):
        triple = [f"{field}{ax}" for ax in "xyz"]
        if all(c in comps for c in triple):
            return field, triple
    return None


def _mirror_signature(array_name: str) -> tuple[str, int | None] | None:
    """``(field, component axis)`` of an exported field array, or ``None``.

    ``Ex`` and ``Hz_im`` name a single component, ``E`` and ``E_re`` the
    3-component vector (component ``None``).  Magnitudes and anything
    unrecognised give ``None``: they are even across every mirror and
    need no correction.
    """
    stem = array_name
    for suffix in ("_re", "_im"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break
    if stem in ("E", "H"):
        return stem, None
    if len(stem) == 2 and stem[0] in ("E", "H") and stem[1] in _COMP_AXES:
        return stem[0], _COMP_AXES[stem[1]]
    return None


def _mirror_signs(array_names, mirrors) -> list[dict]:
    """Per mirror plane, the continuation sign of every field array.

    ``{name: ±1.0}`` for a single component, ``{name: [sx, sy, sz]}``
    for a vector — the rule of :func:`~magnelio.post._symmetry.mirror_sign`
    (E polar across a magnetic wall and axial across an electric one, H
    the other way round), applied inside the session's field filter
    where the mirrored copy is built in numpy.  Magnitudes and anything
    unrecognised are left out: they are even and the filter defaults to
    ``+1``.
    """
    from magnelio.post._symmetry import mirror_sign  # noqa: PLC0415

    out = []
    for axis, _wall, _at_low, kind in mirrors:
        mirror_axis = _COMP_AXES[axis]
        plane: dict = {}
        for name in array_names:
            signature = _mirror_signature(name)
            if signature is None:
                continue
            field, comp = signature
            if comp is None:
                plane[name] = [mirror_sign(field, c, mirror_axis, kind) for c in range(3)]
            else:
                plane[name] = mirror_sign(field, comp, mirror_axis, kind)
        out.append(plane)
    return out


def _prepare_mirroring(monitors, mirrors) -> None:
    """Resolve each monitor spec against the declared mirror planes.

    Two edits, both in place.  The continuation signs replace the raw
    array listing, and a monitor collapsed onto a mirrored axis gets its
    second sampling layer: mirroring turns its single cell layer into
    two, and a lattice of one would sample the seam between them instead.

    The lattice is deliberately *not* widened otherwise.  Its spacing is
    sized for a target arrow count in the displayed picture, and the
    displayed picture is the mirrored one — keeping the dimensions puts
    that target on the full model rather than on each half.
    """
    for spec in monitors:
        spec["mirror_signs"] = _mirror_signs(spec.pop("field_arrays", []), mirrors)
        for axis, _wall, _at_low, _kind in mirrors:
            index = _COMP_AXES[axis]
            for key in ("resample_dims", "resample_dims_volume"):
                dims = spec.get(key)
                if dims and dims[index] == 1:
                    dims[index] = 2


def _sample_steps(n: int, k: int = _CAP_TIME_SAMPLES) -> list[int]:
    return sorted(set(np.linspace(0, n - 1, min(k, n)).astype(int).tolist()))


def _spatial_stride(shape) -> tuple[slice, ...]:
    total = int(np.prod(shape))
    if total <= _CAP_MAX_SAMPLES:
        return (slice(None),) * len(shape)
    s = int(np.ceil((total / _CAP_MAX_SAMPLES) ** (1.0 / len(shape))))
    return tuple(slice(None, None, s) for _ in shape)


def _magnitude_stats(component_steps, percentile: float) -> tuple[float, float]:
    """Glyph clip cap and length reference from sampled ``|v|``.

    ``component_steps`` yields, per sampled step, the list of component
    arrays (already spatially subsampled).  Two *different* numbers come
    out of the pooled magnitudes, and conflating them makes the glyphs
    unusable (DD-115 follow-up):

    * **cap** — the high percentile at which arrow length saturates, so
      edge singularities keep their direction without dictating the
      scale.  Taken over all samples.
    * **reference** — the magnitude that maps to the full arrow length.
      Taken over the *field-carrying* cells only (above 1 % of the
      maximum): a monitor spanning the whole domain is typically half
      zeros — PEC interiors and quiet volume — and a percentile over
      those puts the reference next to the maximum, which renders the
      typical arrow sub-millimetre.
    """
    chunks = []
    for comps in component_steps:
        m2 = None
        for a in comps:
            a = np.abs(np.asarray(a, dtype=np.complex128 if np.iscomplexobj(a) else np.float64))
            m2 = a * a if m2 is None else m2 + a * a
        chunks.append(np.sqrt(np.real(m2)).ravel())
    vals = np.concatenate(chunks) if chunks else np.zeros(0)
    if vals.size == 0 or not np.any(vals > 0.0):
        return 0.0, 1.0
    cap = float(np.percentile(vals, percentile))
    live = vals[vals > _LIVE_CELL_FRACTION * vals.max()]
    ref = float(np.percentile(live, _REFERENCE_PERCENTILE)) if live.size else cap
    if cap <= 0.0:
        return 0.0, 1.0
    return cap, _length_exponent(ref, cap)


def _length_exponent(reference: float, cap: float) -> float:
    """Exponent mapping *reference* to a fixed fraction of the full length.

    The glyph length factor is ``(m/cap) ** exponent``.  Solving
    ``(reference/cap) ** e == _REFERENCE_LENGTH_FRACTION`` puts the
    typical field-carrying magnitude at a visible length while the cap
    still maps to exactly 1, so the longest arrow stays bounded.  A
    linear map falls out (exponent 1) when the reference already sits at
    that fraction; heavier-tailed distributions compress harder.
    """
    lo, hi = _EXPONENT_LIMITS
    if not 0.0 < reference < cap:
        return hi
    e = float(np.log(_REFERENCE_LENGTH_FRACTION) / np.log(reference / cap))
    return float(min(max(e, lo), hi))


def _monitor_geometry(node_x, node_y, node_z) -> dict:
    """Slice-plane spec derived from a monitor's node coordinates."""
    nodes = [np.asarray(node_x), np.asarray(node_y), np.asarray(node_z)]
    ext = [float(a[-1] - a[0]) for a in nodes]
    center = [float(0.5 * (a[0] + a[-1])) for a in nodes]
    ncells = [len(a) - 1 for a in nodes]
    axes = ["x", "y", "z"]
    degenerate = [ax for ax, n in zip(axes, ncells) if n <= 1]
    diag = float(np.sqrt(sum(e * e for e in ext)))
    # A single-cell axis is degenerate for the lattice even though it has
    # a physical thickness: a plane monitor must resample to one layer,
    # not to several through a thickness that carries no second sample.
    lat_ext = [0.0 if n <= 1 else e for e, n in zip(ext, ncells)]
    spec = {
        "center": center,
        "slice_axes": [],
        "default_axis": None,
        "planar_normal": None,
        "resample_dims": _lattice_dims(lat_ext, _section_step(lat_ext)),
        "resample_dims_volume": None,
        "l_ref": max(diag * _GLYPH_LENGTH_FRACTION, 1e-12),
    }
    if not degenerate:
        spec["slice_axes"] = axes
        # Cutting normal to the shortest extent exposes the largest
        # section area — the natural first view of a 3D monitor.
        spec["default_axis"] = axes[int(np.argmin(ext))]
        step = _volume_step(lat_ext)
        if step:
            spec["resample_dims_volume"] = _lattice_dims(lat_ext, step)
    elif len(degenerate) == 1:
        spec["planar_normal"] = degenerate[0]
    return spec


def _lattice_dims(extents, step: float) -> list[int]:
    """Grid dimensions for *step* spacing; degenerate axes collapse to 1.

    One spacing for every axis, deliberately: a fixed sample count per
    axis would make the spacing directional on an elongated region —
    exactly the bias that placing arrows on the computational grid
    produced in the first place.
    """
    return [
        1 if e <= 0.0 else int(min(max(round(e / step) + 1, 2), _RESAMPLE_MAX_PER_AXIS))
        for e in extents
    ]


def _section_step(extents) -> float:
    """Lattice spacing giving ~``_ARROWS_PER_SECTION`` arrows in a cut.

    Sized from the *largest* section through the region (the plane
    spanning the two longest extents, which is also the default cut), so
    that view lands on the target and the narrower cuts scale down with
    their own area rather than being starved.
    """
    live = sorted((float(e) for e in extents if e > 0.0), reverse=True)
    if len(live) < 2:
        return live[0] / 8.0 if live else 1.0
    return float(np.sqrt(live[0] * live[1] / _ARROWS_PER_SECTION))


def _volume_step(extents) -> float | None:
    """Lattice spacing for a bounded arrow count in the volume view."""
    live = [float(e) for e in extents if e > 0.0]
    if len(live) < 3:
        return None
    return float((live[0] * live[1] * live[2] / _RESAMPLE_VOLUME_POINTS) ** (1.0 / 3.0))


def _vector_triples(components) -> list[tuple[str, list[str]]]:
    """Every complete field triple among *components*, E first."""
    comps = set(components)
    out = []
    for field in ("E", "H"):
        triple = [f"{field}{ax}" for ax in "xyz"]
        if all(c in comps for c in triple):
            out.append((field, triple))
    return out


def _write_pvd(pv_dir: Path, safe: str, entries) -> None:
    lines = [
        '<?xml version="1.0"?>',
        '<VTKFile type="Collection" version="0.1">',
        "  <Collection>",
    ]
    lines += [
        f'    <DataSet timestep="{value:.9e}" part="0" file="{rel}"/>' for value, rel in entries
    ]
    lines += ["  </Collection>", "</VTKFile>", ""]
    (pv_dir / f"{safe}.pvd").write_text("\n".join(lines), encoding="utf-8")


def _export_time_monitor(run_dir: Path, pv_dir: Path, name: str, percentile: float):
    """``.vtr``-per-frame series + ``.pvd`` collection + pipeline spec, or ``None``.

    The store holds the frames as grid quantities on the region's Yee
    positions (DD-259); each frame is averaged onto the cell centres
    here, at export time, and written as cell data — the same quantity
    the monitor's own ``.data`` reports.
    """
    import vtk  # noqa: PLC0415
    from vtk.util import numpy_support as ns  # noqa: PLC0415

    from magnelio.io.project import _LoadedFieldMonitor  # noqa: PLC0415

    reader = _LoadedFieldMonitor(run_dir, name)
    times = np.asarray(reader.t, dtype=float)
    n = int(times.size)
    components = list(reader.components)
    if n == 0 or not components:
        return None
    g = reader.grid
    node_x, node_y, node_z = (np.asarray(a, dtype=float) for a in (g.x, g.y, g.z))
    triples = _vector_triples(components)
    vec = _pick_vector(components)

    cap, exponent = 0.0, 1.0
    if vec is not None:
        sl = _spatial_stride((g.Nx, g.Ny, g.Nz))

        def steps():
            for ti in _sample_steps(n):
                cc = reader.frame(ti).cell_centred(vec[1])
                yield [cc[c][sl] for c in vec[1]]

        cap, exponent = _magnitude_stats(steps(), percentile)

    safe = _sanitize(name)
    mon_dir = pv_dir / safe
    mon_dir.mkdir(parents=True, exist_ok=True)
    entries = []
    for ti in range(n):
        cc = reader.frame(ti).cell_centred(components)
        rg = _freq_vtr_grid(node_x, node_y, node_z)
        cd = rg.GetCellData()

        def add(name_, data):
            arr = ns.numpy_to_vtk(np.ascontiguousarray(data, dtype=np.float64), deep=True)
            arr.SetName(name_)
            cd.AddArray(arr)

        for c in components:
            add(c, _flat_cells(cc[c]))
        for field, triple in triples:
            add(field, np.stack([_flat_cells(cc[c]) for c in triple], axis=-1))

        writer = vtk.vtkXMLRectilinearGridWriter()
        rel = f"{safe}/t_{ti:04d}.vtr"
        writer.SetFileName(str(pv_dir / rel))
        writer.SetInputData(rg)
        writer.Write()
        entries.append((float(times[ti]), rel))
    _write_pvd(pv_dir, safe, entries)

    spec = _monitor_geometry(node_x, node_y, node_z)
    spec.update(
        {
            "name": name,
            "kind": "time",
            "data": f"paraview/{safe}.pvd",
            "reader": "pvd",
            "glyph": None,
            "field_arrays": list(components) + [field for field, _ in triples],
        }
    )
    if vec is not None and cap > 0.0:
        spec["glyph"] = {
            "arrays": [vec[0]],
            "cap": cap,
            "exponent": exponent,
            "length": spec["l_ref"],
            "threshold": cap * _VOLUME_THRESHOLD_FRACTION,
        }
    return spec


def _freq_vtr_grid(node_x, node_y, node_z):
    import vtk  # noqa: PLC0415
    from vtk.util import numpy_support as ns  # noqa: PLC0415

    rg = vtk.vtkRectilinearGrid()
    rg.SetDimensions(len(node_x), len(node_y), len(node_z))
    setters = (rg.SetXCoordinates, rg.SetYCoordinates, rg.SetZCoordinates)
    for axis, nodes, setter in zip("xyz", (node_x, node_y, node_z), setters):
        arr = ns.numpy_to_vtk(np.asarray(nodes, dtype=np.float64), deep=True)
        # Unnamed VTK arrays are written as "Array 0x<address>", which
        # makes the file differ between processes for identical data.
        # Naming them keeps the export byte-reproducible.
        arr.SetName(f"{axis}_nodes")
        setter(arr)
    return rg


def _flat_cells(a: np.ndarray) -> np.ndarray:
    """Monitor-native ``(nx, ny, nz)`` -> VTK cell order (x fastest)."""
    return np.ascontiguousarray(a.transpose(2, 1, 0)).ravel()


def _run_source_spectrum(run_dir: Path, freqs: np.ndarray):
    """The run's excitation transformed at *freqs*, or ``None`` if absent.

    Reads through the store's own run reader rather than reaching into
    ``results.h5``: that reader truncates every stream to their common
    prefix, so a run cut short yields the same waveform here as it does
    through :class:`~magnelio.io.project.Project` — and therefore the
    same spectrum, to the last bit.
    """
    from magnelio.io.project import _read_run_results  # noqa: PLC0415
    from magnelio.monitors._dft import source_spectrum  # noqa: PLC0415

    try:
        sig = _read_run_results(run_dir)["reference"]
    except (OSError, KeyError):
        return None
    return source_spectrum(sig.values, sig.dt, freqs)


def _export_freq_monitor(run_dir: Path, pv_dir: Path, name: str, grid, percentile: float):
    """``.vtr``-per-frequency series + ``.pvd`` collection + pipeline spec.

    The store holds the bins as grid quantities on the region's Yee
    positions (DD-259); each frequency is averaged onto the cell centres
    here, at export time.
    """
    import vtk  # noqa: PLC0415
    from vtk.util import numpy_support as ns  # noqa: PLC0415

    from magnelio.io.project import _LoadedFreqMonitor  # noqa: PLC0415

    reader = _LoadedFreqMonitor(run_dir, name, grid=grid)
    components = list(reader.components)
    freqs = np.asarray(reader.f, dtype=float)
    if freqs.size == 0 or not components:
        return None
    # Ship the same quantity the monitor's own ``.data`` reports — fields
    # per 1 W CW — so a value read off the renderer means what a value
    # read in Python means.  A run without a stored excitation (none in
    # practice) exports the raw bins rather than nothing.
    mon = reader._hydrate()
    spectrum = _run_source_spectrum(run_dir, freqs)
    if spectrum is not None:
        mon._source_spectrum = spectrum
    spec_series = mon._spectrum(spectrum is not None)
    g = spec_series.grid
    node_x, node_y, node_z = (np.asarray(a, dtype=float) for a in (g.x, g.y, g.z))

    safe = _sanitize(name)
    mon_dir = pv_dir / safe
    mon_dir.mkdir(parents=True, exist_ok=True)

    vec = _pick_vector(components)
    entries = []
    for fi, f_val in enumerate(freqs):
        bins = spec_series.cell_centred(components, frame=fi)
        rg = _freq_vtr_grid(node_x, node_y, node_z)
        cd = rg.GetCellData()

        def add(name_, data):
            arr = ns.numpy_to_vtk(np.ascontiguousarray(data, dtype=np.float64), deep=True)
            arr.SetName(name_)
            cd.AddArray(arr)

        for c in components:
            a = bins[c]
            add(f"{c}_re", _flat_cells(a.real))
            add(f"{c}_im", _flat_cells(a.imag))
        if vec is not None:
            field, triple = vec
            re = np.stack([_flat_cells(bins[c].real) for c in triple], axis=-1)
            im = np.stack([_flat_cells(bins[c].imag) for c in triple], axis=-1)
            add(f"{field}_re", re)
            add(f"{field}_im", im)
            add(f"|{field}|", np.sqrt(np.sum(re * re + im * im, axis=-1)))

        writer = vtk.vtkXMLRectilinearGridWriter()
        rel = f"{safe}/f_{fi:04d}.vtr"
        writer.SetFileName(str(pv_dir / rel))
        writer.SetInputData(rg)
        writer.Write()
        entries.append((f_val, rel))

    _write_pvd(pv_dir, safe, entries)

    field_arrays = [f"{c}_{part}" for c in components for part in ("re", "im")]
    if vec is not None:
        field_arrays += [f"{vec[0]}_re", f"{vec[0]}_im"]
    spec = _monitor_geometry(node_x, node_y, node_z)
    spec.update(
        {
            "name": name,
            "kind": "freq",
            "data": f"paraview/{safe}.pvd",
            "reader": "pvd",
            "glyph": None,
            "field_arrays": field_arrays,
        }
    )
    if vec is not None:
        field, triple = vec
        sl = _spatial_stride(spec_series.shape)

        def steps():
            for fi in _sample_steps(len(freqs)):
                cc = spec_series.cell_centred(triple, frame=fi)
                yield [cc[c][sl] for c in triple]

        cap, exponent = _magnitude_stats(steps(), percentile)
        if cap > 0.0:
            # Real and imaginary part each get their own glyph set: they
            # are the field at phase 0 and at phase −90°, and together
            # they span the full ellipse — where one nearly vanishes the
            # other carries the field, so offering only the real part
            # hides half the picture.  Both share the cap and reference
            # from the complex magnitude, which bounds either phase.
            spec["glyph"] = {
                "arrays": [f"{field}_re", f"{field}_im"],
                "cap": cap,
                "exponent": exponent,
                "length": spec["l_ref"],
                "threshold": cap * _VOLUME_THRESHOLD_FRACTION,
            }
    return spec


def _eigenmode_fields(mode_arrays: dict, grid):
    """One stored eigenmode as cell-centred E and H, peak-normalised.

    The stored arrays are the solver's FIT grid quantities (edge
    voltages / face currents), so they go through the same
    ``_interp_to_cell_centres`` conversion the field monitors use
    (DD-085).  An eigenvector carries no absolute amplitude — the
    solver's own scaling ran to 1e8 on the tutorial-13 cavity, which
    reads as V/m and is not — so each field is divided by its own peak
    magnitude.  The two divisors are returned with the fields: they are
    the only thing lost, and writing them into the file keeps the
    normalisation reversible.
    """
    from magnelio._fields.field_arrays import FieldArrays  # noqa: PLC0415
    from magnelio.monitors.base import _interp_to_cell_centres  # noqa: PLC0415

    state = FieldArrays(**mode_arrays)
    cells = _interp_to_cell_centres(
        state,
        ["Ex", "Ey", "Ez", "Hx", "Hy", "Hz"],
        slice(0, grid.Nx),
        slice(0, grid.Ny),
        slice(0, grid.Nz),
        grid,
    )
    scales = {}
    for field in ("E", "H"):
        triple = [cells[f"{field}{ax}"] for ax in "xyz"]
        peak = float(np.sqrt(sum(np.asarray(c, dtype=float) ** 2 for c in triple)).max())
        scales[field] = peak if peak > 0.0 else 1.0
        for ax in "xyz":
            cells[f"{field}{ax}"] = np.asarray(cells[f"{field}{ax}"], dtype=float) / scales[field]
    return cells, scales


def _export_eigenmodes(project_path: Path, pv_dir: Path, grid, percentile: float):
    """``.vtr``-per-mode series + ``.pvd`` collection + pipeline spec.

    The ParaView axis carries the **mode index**, not the eigenfrequency:
    degenerate pairs share a frequency to the last digit (they are the
    rule, not the exception, in any symmetric cavity), and two datasets
    at one timestep hide each other.  The frequency travels as field
    data instead, so it is still displayed and still exact.
    """
    import h5py  # noqa: PLC0415
    import vtk  # noqa: PLC0415
    from vtk.util import numpy_support as ns  # noqa: PLC0415

    src = project_path / "eigenmodes.h5"
    if not src.exists():
        return None
    comps = ["Ex", "Ey", "Ez", "Hx", "Hy", "Hz"]
    with h5py.File(src, "r") as f:
        freqs = np.asarray(f["frequencies"][()], dtype=float)
        raw = [{c: f[f"mode_{i:03d}"][c][()] for c in comps} for i in range(freqs.size)]
    if freqs.size == 0:
        return None

    node_x, node_y, node_z = np.asarray(grid.x), np.asarray(grid.y), np.asarray(grid.z)
    mon_dir = pv_dir / "eigenmodes"
    mon_dir.mkdir(parents=True, exist_ok=True)

    entries = []
    cell_fields = []
    for i, mode_arrays in enumerate(raw):
        cells, scales = _eigenmode_fields(mode_arrays, grid)
        cell_fields.append(cells)
        rg = _freq_vtr_grid(node_x, node_y, node_z)
        cd = rg.GetCellData()
        for c in comps:
            arr = ns.numpy_to_vtk(_flat_cells(cells[c]), deep=True)
            arr.SetName(c)
            cd.AddArray(arr)
        for field in ("E", "H"):
            vec = np.stack([_flat_cells(cells[f"{field}{ax}"]) for ax in "xyz"], axis=-1)
            arr = ns.numpy_to_vtk(np.ascontiguousarray(vec), deep=True)
            arr.SetName(field)
            cd.AddArray(arr)
            mag = ns.numpy_to_vtk(np.sqrt(np.sum(vec * vec, axis=-1)), deep=True)
            mag.SetName(f"|{field}|")
            cd.AddArray(mag)
        # Provenance of this file, and the inverse of the normalisation.
        for label, value in (
            ("f_Hz", float(freqs[i])),
            ("mode_index", float(i)),
            ("E_peak_before_normalisation", scales["E"]),
            ("H_peak_before_normalisation", scales["H"]),
        ):
            fd = ns.numpy_to_vtk(np.array([value], dtype=np.float64), deep=True)
            fd.SetName(label)
            rg.GetFieldData().AddArray(fd)

        writer = vtk.vtkXMLRectilinearGridWriter()
        rel = f"eigenmodes/mode_{i:04d}.vtr"
        writer.SetFileName(str(pv_dir / rel))
        writer.SetInputData(rg)
        writer.Write()
        entries.append(rel)

    pvd_lines = [
        '<?xml version="1.0"?>',
        '<VTKFile type="Collection" version="0.1">',
        "  <Collection>",
    ]
    pvd_lines += [
        f'    <DataSet timestep="{i:d}" part="0" file="{rel}"/>' for i, rel in enumerate(entries)
    ]
    pvd_lines += ["  </Collection>", "</VTKFile>", ""]
    (pv_dir / "eigenmodes.pvd").write_text("\n".join(pvd_lines), encoding="utf-8")

    spec = _monitor_geometry(node_x, node_y, node_z)
    spec.update(
        {
            "name": "eigenmodes",
            "kind": "eigenmode",
            "data": "paraview/eigenmodes.pvd",
            "reader": "pvd",
            "glyph": None,
            "field_arrays": [*comps, "E", "H"],
        }
    )
    sl = _spatial_stride(cell_fields[0]["Ex"].shape)

    def steps():
        for i in _sample_steps(len(cell_fields)):
            yield [cell_fields[i][f"E{ax}"][sl] for ax in "xyz"]

    cap, exponent = _magnitude_stats(steps(), percentile)
    if cap > 0.0:
        # E only: the modes are peak-normalised per field, so an H glyph
        # set would be drawn at the same lengths from an unrelated
        # scaling — visually equal, physically incomparable.
        spec["glyph"] = {
            "arrays": ["E"],
            "cap": cap,
            "exponent": exponent,
            "length": spec["l_ref"],
            "threshold": cap * _VOLUME_THRESHOLD_FRACTION,
        }
    return spec


# ═════════════════════════════════════════════════════════════════════
# Session generation: paraview_open.py + baked paraview.pvsm
# ═════════════════════════════════════════════════════════════════════

#: Where bake_pvsm writes the version of the ParaView that baked the
#: state file; the placeholder stands while no state has been baked.
_STAMP_PREFIX = "# paraview.pvsm beside this script was baked by ParaView "
_STAMP_NONE = "(not baked)"

_SCRIPT_HEADER = f"""\
# Generated by magnelio (DD-115, DD-262, DD-265) — a ready-to-open ParaView session.
#
#   Open in the GUI:   paraview --script=paraview_open.py
#   Bake a state file: pvpython paraview_open.py --save-state paraview.pvsm
#
# This script builds the session live and works on any ParaView that can
# run it.  A .pvsm state file cannot: it names proxies by the spelling of
# the release that wrote it, and a renamed proxy takes its whole branch
# of the pipeline down without replacing it.  Open the state only with
# the version named here, and this script with any other.
{_STAMP_PREFIX}{_STAMP_NONE}
#
# Regenerated by Project.export_paraview(); manual edits will be lost.
import json
import os
import sys

import numpy

# ParaView 6.0 ships a numpy_interface that still calls numpy.in1d, gone
# in numpy 2.4; every Python filter dies in its preamble without this.
if not hasattr(numpy, "in1d"):
    numpy.in1d = numpy.isin

"""

# The three scripts of the per-monitor ProgrammableFilter (DD-262).  They
# run inside ParaView's Python, whose filter preamble does
# ``from ...numpy_interface.algorithms import *`` and thereby shadows
# ``max``, ``min``, ``abs``, ``sum``, ``any`` and ``all`` with array
# reductions — hence only ``np.`` functions below.  ``CFG`` and ``MODE``
# are prepended by the session script (a ``Parameters`` property exists
# on the proxy but cannot be set from pvpython 6.0).
_FIELD_SCRIPT = """\
import numpy as np
from vtkmodules.vtkCommonCore import vtkPoints
from vtkmodules.vtkCommonDataModel import vtkCellArray, vtkPolyData, vtkRectilinearGrid
from vtkmodules.vtkFiltersCore import vtkCellDataToPointData, vtkResampleToImage
from vtkmodules.util import numpy_support as ns

inp = self.GetInputDataObject(0, 0)
out = self.GetOutputDataObject(0)

# The stored frame: cell data on the monitor's node grid, x fastest.
dims = list(inp.GetDimensions())
coords = [ns.vtk_to_numpy(getattr(inp, "Get%sCoordinates" % ax)()).astype(float) for ax in "XYZ"]
ncell = [d - 1 if d > 1 else 1 for d in dims]
cd = inp.GetCellData()
cells = {}
for i in range(cd.GetNumberOfArrays()):
    a = cd.GetArray(i)
    if a is None:
        continue
    cells[a.GetName()] = ns.vtk_to_numpy(a).reshape(ncell[2], ncell[1], ncell[0], -1)

# Symmetry planes: the simulated half on disk, the whole model here.
# Each component continues with its own sign (CFG["signs"]); a wall on
# a grid line (PEC) reflects its node onto itself, a magnetic wall half
# a cell outside the grid leaves one cell astride it, which takes the
# wall value: the edge value for an even component, zero for an odd one.
for pi, plane in enumerate(CFG.get("symmetry") or []):
    axis, wall, at_low = "xyz".index(plane[0]), float(plane[1]), bool(plane[2])
    signs = CFG["signs"][pi] if pi < len(CFG["signs"]) else {}
    npax = 2 - axis
    c = coords[axis]
    tol = 1e-9 * np.maximum(np.abs(float(c[-1] - c[0])), 1e-300)
    refl = 2.0 * wall - c[::-1]
    if at_low:
        gap = np.abs(float(refl[-1] - c[0])) > tol
        if not gap:
            refl = refl[:-1]
        coords[axis] = np.concatenate([refl, c])
    else:
        gap = np.abs(float(refl[0] - c[-1])) > tol
        if not gap:
            refl = refl[1:]
        coords[axis] = np.concatenate([c, refl])
    for name, a in list(cells.items()):
        s = np.asarray(signs.get(name, 1.0), dtype=float).reshape(-1)
        flipped = np.flip(a, axis=npax) * s
        parts = [flipped]
        if gap:
            edge = np.take(a, [0] if at_low else [-1], axis=npax)
            parts.append(0.5 * (edge + edge * s))
        cells[name] = np.concatenate(parts + [a] if at_low else [a] + parts[::-1], axis=npax)

rg = vtkRectilinearGrid()
rg.SetDimensions(len(coords[0]), len(coords[1]), len(coords[2]))
for ax, c in zip("XYZ", coords):
    getattr(rg, "Set%sCoordinates" % ax)(ns.numpy_to_vtk(np.ascontiguousarray(c), deep=True))
for name, a in cells.items():
    flat = np.ascontiguousarray(a).reshape(-1, a.shape[-1])
    arr = ns.numpy_to_vtk(flat if flat.shape[1] > 1 else flat[:, 0].copy(), deep=True)
    arr.SetName(name)
    rg.GetCellData().AddArray(arr)

# Cell averages to the nodes, then onto the even lattice: arrows are
# never placed on the computational grid, whose spacing varies by a
# factor of 40 and would read as crowded planes with voids between.
c2p = vtkCellDataToPointData()
c2p.SetInputData(rg)
c2p.PassCellDataOff()
res = vtkResampleToImage()
res.SetInputConnection(c2p.GetOutputPort())
res.SetUseInputBounds(True)
res.SetSamplingDimensions(*(CFG["dims_volume"] if MODE == "volume" else CFG["dims"]))
res.Update()
img = res.GetOutput()
pd = img.GetPointData()

# Arrow length law: (min(|v|, cap) / cap) ** exponent.  The cap
# saturates the edge singularities, the exponent (fitted at export
# time) keeps the typical field-carrying magnitude visible.
cap, expo = float(CFG["cap"]), float(CFG["exponent"])
lengths = {}
for arr in CFG["arrays"]:
    v = ns.vtk_to_numpy(pd.GetArray(arr))
    m = np.sqrt(np.sum(v * v, axis=-1))
    lengths[arr] = (m, (np.minimum(m, cap) / cap) ** expo if cap > 0.0 else np.zeros_like(m))

if MODE == "volume":
    # A point cloud of the lattice points carrying field, for the
    # volume arrows: a whole-domain monitor is mostly quiet volume.
    keep = np.zeros(img.GetNumberOfPoints(), dtype=bool)
    for arr in CFG["arrays"]:
        keep |= lengths[arr][0] >= float(CFG["threshold"])
    idx = np.nonzero(keep)[0]
    dx, dy, _dz = img.GetDimensions()
    ijk = np.stack([idx % dx, (idx // dx) % dy, idx // (dx * dy)], axis=-1)
    xyz = np.asarray(img.GetOrigin()) + ijk * np.asarray(img.GetSpacing())
    poly = vtkPolyData()
    pts = vtkPoints()
    pts.SetData(ns.numpy_to_vtk(np.ascontiguousarray(xyz, dtype=float), deep=True))
    poly.SetPoints(pts)
    n = int(idx.size)
    verts = vtkCellArray()
    verts.SetData(
        ns.numpy_to_vtkIdTypeArray(np.arange(n + 1, dtype=np.int64), deep=True),
        ns.numpy_to_vtkIdTypeArray(np.arange(n, dtype=np.int64), deep=True),
    )
    poly.SetVerts(verts)
    for i in range(pd.GetNumberOfArrays()):
        a = pd.GetArray(i)
        if a is None or a.GetName() in ("vtkValidPointMask", "vtkGhostType"):
            continue
        va = ns.numpy_to_vtk(np.ascontiguousarray(ns.vtk_to_numpy(a)[idx]), deep=True)
        va.SetName(a.GetName())
        poly.GetPointData().AddArray(va)
    for arr in CFG["arrays"]:
        for suffix, val in (("_mag", lengths[arr][0][idx]), ("_len", lengths[arr][1][idx])):
            va = ns.numpy_to_vtk(np.ascontiguousarray(val), deep=True)
            va.SetName(arr + suffix)
            poly.GetPointData().AddArray(va)
    out.ShallowCopy(poly)
else:
    for arr in CFG["arrays"]:
        for suffix, val in (("_mag", lengths[arr][0]), ("_len", lengths[arr][1])):
            va = ns.numpy_to_vtk(np.ascontiguousarray(val), deep=True)
            va.SetName(arr + suffix)
            pd.AddArray(va)
    pd.RemoveArray("vtkValidPointMask")
    out.ShallowCopy(img)
"""

# Declares the lattice extent up front; without it the executive
# renegotiates and runs the field script four times per update.
_INFO_SCRIPT = """\
executive = self.GetExecutive()
outInfo = executive.GetOutputInformation(0)
d = CFG["dims"]
outInfo.Set(executive.WHOLE_EXTENT(), 0, d[0] - 1, 0, d[1] - 1, 0, d[2] - 1)
"""

_UPDATE_SCRIPT = """\
executive = self.GetExecutive()
inInfo = executive.GetInputInformation(0, 0)
inInfo.Set(executive.UPDATE_EXTENT(), inInfo.Get(executive.WHOLE_EXTENT()), 6)
"""

_SCRIPT_BODY = """

def _abspath(rel):
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, rel))


def build():
    try:
        from paraview import servermanager, simple
    except ImportError as exc:
        # Typing "python paraview_open.py" lands here, and the message
        # Python gives is misleading: the sibling data directory is
        # called "paraview" too, so the import finds a namespace package
        # and reports "unknown location" rather than "no ParaView".
        raise SystemExit(
            "paraview_open.py is a ParaView session script and needs ParaView's own "
            "interpreter, not a plain Python.\\n"
            "    paraview --script=paraview_open.py\\n"
            "    pvpython paraview_open.py --save-state paraview.pvsm\\n"
            "A Flatpak ParaView is reached through its runner:\\n"
            "    flatpak run org.paraview.ParaView --script=paraview_open.py\\n"
            "(the import said: %s)" % exc
        ) from exc

    try:
        simple._DisableFirstRenderCameraReset()
    except Exception:
        pass
    view = simple.GetActiveViewOrCreate("RenderView")

    normals = {"x": [1.0, 0.0, 0.0], "y": [0.0, 1.0, 0.0], "z": [0.0, 0.0, 1.0]}

    def link_planes(name, planes):
        # ONE cutting plane for the whole session (DD-266): the geometry
        # clip and every monitor's slice are linked in both directions,
        # so dragging any one of them drags them all and the solids are
        # always opened where the field is shown.  Registered links
        # survive into saved state files.  Best-effort: purely cosmetic.
        if len(planes) < 2:
            return
        try:
            link = servermanager.vtkSMProxyLink()
            for plane in planes:
                link.AddLinkedProxy(plane.SMProxy, 1)  # input
                link.AddLinkedProxy(plane.SMProxy, 2)  # output
            servermanager.ProxyManager().RegisterLink(name, link)
        except Exception:
            pass

    def clip_geometry(origin, normal):
        # The one geometry cut of the session.  Its plane joins the
        # link below, so it opens the solids wherever the field is cut.
        clip = simple.Clip(registrationName="geometry_cut", Input=geom)
        clip.ClipType = "Plane"
        clip.ClipType.Origin = origin
        clip.ClipType.Normal = normal
        return clip

    # -- geometry: coloured per material via categorical LUT -----------
    # ``geometry.vtm`` already holds the WHOLE model: the export clips
    # the solids to the simulated half and mirrors them across every
    # declared symmetry plane in its own VTK (DD-265).  ParaView's
    # reflection filter is not used — its proxy was renamed between 6.0
    # and 6.1, and a state file naming the old one loses the whole
    # geometry branch on the newer release.
    geom = None
    if CONFIG.get("geometry") and os.path.exists(_abspath(CONFIG["geometry"])):
        geom = simple.XMLMultiBlockDataReader(
            registrationName="geometry", FileName=[_abspath(CONFIG["geometry"])]
        )
        disp = simple.Show(geom, view)
        disp.Representation = "Surface"
        simple.ColorBy(disp, ("CELLS", "MaterialIndex"))
        lut = simple.GetColorTransferFunction("MaterialIndex")
        lut.InterpretValuesAsCategories = 1
        annotations, colors, opacities = [], [], []
        for i, mat in enumerate(CONFIG["materials"]):
            annotations += [str(i), mat["name"]]
            colors += [float(c) for c in mat["rgba"][:3]]
            opacities.append(float(mat["rgba"][3]))
        lut.Annotations = annotations
        lut.IndexedColors = colors
        try:
            lut.IndexedOpacities = opacities
            lut.EnableOpacityMapping = 1
        except Exception:
            pass
        disp.Opacity = 0.85

    # -- monitors ------------------------------------------------------
    # One Python filter per monitor holds the whole preparation (mirror,
    # cell-to-point, lattice, arrow lengths); what remains in the
    # pipeline browser is the reader, the field, one cut with its
    # arrows, and the hidden volume arrows.  The geometry is clipped
    # ONCE for the whole session (DD-266) and shares its plane with
    # every monitor's slice.
    shown_any = False
    geom_clip = None
    cut_planes = []
    for mon in CONFIG["monitors"]:
        path = _abspath(mon["data"])
        if not os.path.exists(path):
            continue
        glyph = mon.get("glyph")
        dims = mon.get("resample_dims")
        if not glyph or not dims:
            continue
        name = mon["name"]
        arrays = glyph["arrays"]
        src = simple.PVDReader(registrationName=name, FileName=path)
        cfg = {
            "dims": dims,
            "dims_volume": mon.get("resample_dims_volume") or dims,
            "arrays": arrays,
            "cap": glyph["cap"],
            "exponent": glyph["exponent"],
            "threshold": glyph["threshold"],
            "symmetry": CONFIG.get("symmetry") or [],
            "signs": mon.get("mirror_signs") or [],
        }

        def programmable(label, mode, output_type, info):
            pf = simple.ProgrammableFilter(registrationName=label, Input=src)
            pf.OutputDataSetType = output_type
            head = "CFG = %r\\nMODE = %r\\n" % (cfg, mode)
            pf.Script = head + FIELD_SCRIPT
            if info:
                pf.RequestInformationScript = head + INFO_SCRIPT
                pf.RequestUpdateExtentScript = UPDATE_SCRIPT
            return pf

        def make_glyph(inp, label, arr):
            gly = simple.Glyph(registrationName=label, Input=inp, GlyphType="Arrow")
            gly.OrientationArray = ["POINTS", arr]
            gly.ScaleArray = ["POINTS", arr + "_len"]
            # The length array is dimensionless 0..1, so the factor is a
            # plain length in metres: the longest arrow drawn.
            gly.ScaleFactor = glyph["length"]
            # The input already IS the even spacing asked for, so every
            # point carries an arrow; any seeding mode would undo it.
            gly.GlyphMode = "All Points"
            try:
                # Centred on the sample point rather than starting there.
                gly.GlyphTransform.Translate = [-0.5, 0.0, 0.0]
            except Exception:
                pass
            return gly

        def coloured(proxy, arr=None, visible=False, bar=False):
            # Every representation is coloured when it is made, whether
            # it is shown now or waits hidden (DD-266): a glyph set
            # switched on later came up in a flat "Solid Color" and had
            # to be coloured by hand, which is what the arrow scale is
            # there to avoid.  The colour carries the TRUE magnitude
            # (linear, un-compressed); only the arrow length is
            # compressed.  Each monitor gets its own transfer function
            # (`separate`), because the cap it is scaled to is its own.
            d = simple.GetDisplayProperties(proxy, view)
            if arr:
                sep = True
                try:
                    d.UseSeparateColorMap = 1
                except Exception:
                    sep = False
                try:
                    lut = simple.GetColorTransferFunction(arr, d, separate=sep)
                except TypeError:  # older paraview.simple
                    sep = False
                    lut = simple.GetColorTransferFunction(arr)
                # Scaled before the array is attached: rescaling after
                # would ask the (possibly unbuilt) data for its range.
                lut.RescaleTransferFunction(0.0, glyph["cap"])
                try:
                    lut.AutomaticRescaleRangeMode = "Never"
                except Exception:
                    pass
                simple.ColorBy(d, ("POINTS", arr, "Magnitude"), separate=sep)
                d.SetScalarBarVisibility(view, bar)
            d.Visibility = 1 if visible else 0
            return d

        is_first = not shown_any
        field = programmable(name + "_field", "section", "vtkImageData", True)

        if mon["slice_axes"]:
            if mon.get("resample_dims_volume"):
                # Whole-volume arrows on their own, coarser lattice, hidden
                # until asked for: glyphing the section lattice in 3D
                # would bury the field under its own arrows.
                vol = programmable(name + "_volume", "volume", "vtkPolyData", False)
                coloured(make_glyph(vol, name + "_volume_arrows", arrays[0]), arrays[0])
            # One cut, normal to the shortest extent (the largest section);
            # the plane widget turns it to any other orientation.
            sl = simple.Slice(registrationName=name + "_slice", Input=field)
            sl.SliceType = "Plane"
            sl.SliceType.Origin = mon["center"]
            sl.SliceType.Normal = normals[mon["default_axis"]]
            cut_planes.append(sl.SliceType)
            arrows = make_glyph(sl, name + "_arrows", arrays[0])
            coloured(arrows, arrays[0], visible=is_first, bar=is_first)
            if len(arrays) > 1:
                # The imaginary part of a frequency monitor: the field a
                # quarter period later, ready one click from visible.
                coloured(make_glyph(sl, name + "_arrows_im", arrays[1]), arrays[1])
            if geom is not None and geom_clip is None:
                geom_clip = clip_geometry(mon["center"], normals[mon["default_axis"]])
            # The sheet carries the same magnitude on the same scale;
            # one scalar bar for the pair is enough.
            coloured(sl, arrays[0], visible=is_first)
            shown_any = shown_any or is_first
        else:
            # Planar (or lower-dimensional) monitor: the lattice already is
            # the section — glyph it directly, no slicing needed.
            arrows = make_glyph(field, name + "_arrows", arrays[0])
            coloured(arrows, arrays[0], visible=is_first, bar=is_first)
            if len(arrays) > 1:
                coloured(make_glyph(field, name + "_arrows_im", arrays[1]), arrays[1])
            if geom is not None and geom_clip is None and mon.get("planar_normal"):
                geom_clip = clip_geometry(mon["center"], normals[mon["planar_normal"]])
            coloured(field, arrays[0], visible=is_first)
            shown_any = shown_any or is_first

    link_planes("cut_plane", cut_planes + ([geom_clip.ClipType] if geom_clip else []))

    try:
        simple.GetAnimationScene().UpdateAnimationUsingDataTimeSteps()
    except Exception:
        pass
    simple.ResetCamera(view)
    try:
        simple.Render(view)
    except Exception:
        pass


build()
argv = sys.argv[1:]
if "--save-state" in argv:
    from paraview.servermanager import vtkSMProxyManager
    from paraview.simple import SaveState

    SaveState(os.path.abspath(argv[argv.index("--save-state") + 1]))
    # Read back by the exporter and written into this script's header:
    # the state file is only good for this version.
    print(VERSION_MARKER + " " + vtkSMProxyManager.GetParaViewSourceVersion())
"""


def write_paraview_script(script_path: str | Path, config: dict) -> Path:
    """Write the generated ``paraview.simple`` pipeline script."""
    script_path = Path(script_path)
    payload = json.dumps(config)
    script_path.write_text(
        _SCRIPT_HEADER
        + f"CONFIG = json.loads({payload!r})\n"
        + f"VERSION_MARKER = {_VERSION_MARKER!r}\n"
        + f"FIELD_SCRIPT = {_FIELD_SCRIPT!r}\n"
        + f"INFO_SCRIPT = {_INFO_SCRIPT!r}\n"
        + f"UPDATE_SCRIPT = {_UPDATE_SCRIPT!r}\n"
        + _SCRIPT_BODY,
        encoding="utf-8",
    )
    return script_path


def resolve_pvpython(pvpython=None) -> list[str] | None:
    """How to start the ``pvpython`` a bake should use, or ``None``.

    Returns the command as a list, ready to be extended with the bake's
    own arguments.  In order: the argument, ``MAGNELIO_PVPYTHON``, then
    the first ``pvpython`` on ``PATH``.  The choice matters because the
    state file a bake writes is only good for the ParaView that wrote it
    — a machine carrying a distribution build beside a downloaded one
    bakes for whichever comes first, which need not be the one that
    opens the session (DD-265).

    Parameters
    ----------
    pvpython : str or Path or sequence of str, optional
        A path to an interpreter, or the command that launches one —
        a sandboxed or containerised ParaView is reached through its
        runner rather than through a file on ``PATH``, e.g.
        ``"flatpak run --command=pvpython org.paraview.ParaView"``.  A
        string is split on whitespace, so pass a sequence when a path
        contains spaces.
    """
    import os  # noqa: PLC0415
    import shlex  # noqa: PLC0415

    named = pvpython or os.environ.get("MAGNELIO_PVPYTHON")
    if not named:
        found = shutil.which("pvpython")
        return [found] if found else None
    parts = [str(named)] if isinstance(named, Path) else list(named)
    if isinstance(named, str):
        parts = shlex.split(named)
    if not parts:
        return None
    resolved = _which(parts[0])
    if resolved is None and len(parts) == 1 and parts[0].strip() != parts[0].split()[0]:
        # One token carrying whitespace and naming nothing: a command
        # someone quoted as a whole.  IPython's ``%set_env VAR="a b c"``
        # keeps the quotes in the value, and shlex then reads the lot as
        # a single argument.  A real path with spaces resolved above and
        # never reaches here.
        parts = parts[0].split()
        resolved = _which(parts[0])
    return None if resolved is None else [resolved, *parts[1:]]


def _which(name: str) -> str | None:
    """*name* as an executable path, or ``None``."""
    return shutil.which(name) or (name if Path(name).is_file() else None)


def _stamp_version(script_path: Path, version: str) -> None:
    """Write the baking ParaView's version into the script's header."""
    # GetParaViewSourceVersion() answers "paraview version 6.1.0".
    version = version.replace("paraview version", "").strip() or version
    try:
        text = script_path.read_text(encoding="utf-8")
        script_path.write_text(
            text.replace(_STAMP_PREFIX + _STAMP_NONE, _STAMP_PREFIX + version, 1),
            encoding="utf-8",
        )
    except OSError:  # pragma: no cover - the script was just written
        pass


def bake_pvsm(
    script_path: str | Path,
    pvsm_path: str | Path,
    timeout: float = 300.0,
    pvpython=None,
) -> bool:
    """Bake the pipeline script into a ``.pvsm`` state file via ``pvpython``.

    Returns ``False`` (without raising) when no ``pvpython`` is found or
    the bake fails — the script remains the portable fallback.  On
    success the baking ParaView's version is written into the script's
    header, because the state file is bound to it.
    ``MAGNELIO_PVSM_BAKE=0`` disables the bake globally (the test suite
    pins this: a ``pvpython`` subprocess per streamed run would dominate
    its runtime); ``MAGNELIO_PVPYTHON`` names the interpreter, or the
    command that launches one (:func:`resolve_pvpython`).
    """
    import os  # noqa: PLC0415

    if os.environ.get("MAGNELIO_PVSM_BAKE", "1") == "0":
        return False
    cmd = resolve_pvpython(pvpython)
    if cmd is None:
        # Silence here is what makes a mistyped setting expensive: the
        # call returns, the state file is simply absent, and nothing
        # says which of the two it was.
        named = pvpython or os.environ.get("MAGNELIO_PVPYTHON")
        if named:
            warnings.warn(
                f"no ParaView state file was baked: {named!r} is not an executable, so "
                f"nothing could run the session script.  Note that a value quoted as a "
                f"whole is one argument, not a command — IPython's %set_env keeps those "
                f"quotes.  The session opens without a state file: "
                f"paraview --script=paraview_open.py",
                UserWarning,
                stacklevel=4,
            )
        else:
            warnings.warn(
                "no ParaView state file was baked: no 'pvpython' on PATH.  Name one in "
                "MAGNELIO_PVPYTHON or in export_paraview(pvpython=...) — a path, or the "
                "command that launches one, e.g. "
                "flatpak run --command=pvpython org.paraview.ParaView.  The session opens "
                "without a state file: paraview --script=paraview_open.py",
                UserWarning,
                stacklevel=4,
            )
        return False
    pvsm_path = Path(pvsm_path)
    cmd = [
        *cmd,
        "--force-offscreen-rendering",
        str(script_path),
        "--save-state",
        str(pvsm_path),
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, check=False)
    except (OSError, subprocess.TimeoutExpired):
        return False
    baked = proc.returncode == 0 and pvsm_path.exists()
    if not baked:
        tail = (proc.stderr or proc.stdout or "").strip().splitlines()[-3:]
        warnings.warn(
            f"no ParaView state file was baked: {' '.join(cmd[: len(cmd) - 4])} exited "
            f"with {proc.returncode} or wrote nothing.  The session opens without one: "
            f"paraview --script=paraview_open.py" + ("\n" + "\n".join(tail) if tail else ""),
            UserWarning,
            stacklevel=4,
        )
    if baked:
        for line in (proc.stdout or "").splitlines():
            if line.startswith(_VERSION_MARKER):
                _stamp_version(Path(script_path), line.split(maxsplit=1)[-1].strip())
                break
    return baked


def _ensure_geometry_vtm(project, mirrors=None) -> None:
    """Tessellate the stored geometry into ``geometry.vtm`` if it is missing.

    The exact ``geometry.brep`` is what the store writes; the multiblock
    mesh ParaView reads is made here, on the first export, whole — the
    solids completed across the declared symmetry planes (DD-265).  The
    planes it was built for are recorded beside it, so a file written
    before the completion (or for other planes) is made again rather
    than shown as a half model.  Best-effort: a tessellation failure (or
    a build without the CAD kernel) warns and the session goes on
    without the solids.
    """
    path = project.path / "geometry.vtm"
    stamp = project.path / "geometry.vtm.json"
    mirrors = [list(m) for m in (mirrors or ())]
    if not (project.path / "geometry.brep").exists():
        return
    if path.exists():
        try:
            written = json.loads(stamp.read_text(encoding="utf-8"))["mirrors"]
        except (OSError, ValueError, KeyError):
            # No stamp: a file from before the completion existed, which
            # is the whole model already when nothing is mirrored.
            written = [] if not mirrors else None
        if written == mirrors:
            return
    try:
        with warnings.catch_warnings():
            # The geometry reader notes thin wires it cannot rebuild;
            # they carry no solid to tessellate anyway.
            warnings.simplefilter("ignore")
            solids = list(project.geometry)
        if solids:
            export_vtm(path, solids, mirrors=mirrors)
            stamp.write_text(json.dumps({"mirrors": mirrors}), encoding="utf-8")
    except Exception as exc:  # viz-only; the field export goes on
        warnings.warn(
            f"geometry.vtm could not be written (the ParaView session shows no solids): {exc}",
            UserWarning,
            stacklevel=2,
        )


def _geometry_config(project_path: Path, rel: str) -> tuple[str | None, list[dict]]:
    """``(relative geometry.vtm path, material table)`` for a session.

    *rel* is the path from the session script's own directory, which
    differs between a run session (two levels down) and the project-level
    eigenmode session (alongside).
    """
    from magnelio.io.project import _material_from_dict  # noqa: PLC0415

    if not (project_path / "geometry.vtm").exists():
        return None, []
    gj_path = project_path / "geometry.json"
    if not gj_path.exists():
        return rel, []
    gj = json.loads(gj_path.read_text(encoding="utf-8"))
    kinds = gj.get("kinds", ["solid"] * len(gj["materials"]))
    file_colors = gj.get("colors") or [None] * len(gj["materials"])
    pairs = [
        (_material_from_dict(d), c)
        for d, c, kind in zip(gj["materials"], file_colors, kinds)
        if kind != "wire"
    ]
    materials, _ = _material_table([m for m, _ in pairs], [c for _, c in pairs])
    return rel, materials


def _symmetry_config(project) -> list:
    """Declared symmetry planes as ``[[axis, wall_m, at_low, kind], ...]``.

    Read from the stored mesh (DD-154); the wall coordinate reuses the
    monitor mirror resolution (PEC on the outermost grid line, PMC half
    the boundary cell outside — the physical mirror plane).  The wall
    *kind* travels with it because it decides the sign every field
    component picks up across the plane.  Empty when the project stores
    no mesh or the mesh declares no symmetry.
    """
    from magnelio.monitors.base import resolve_mirrors, resolve_region  # noqa: PLC0415

    try:
        mesh = project.mesh
    except Exception:  # noqa: BLE001 — no stored mesh
        return []
    if mesh is None:
        return []
    mirrors = resolve_mirrors(resolve_region(None, mesh.grid), mesh)
    return [["xyz"[m.axis], m.wall, m.at_low, m.kind] for m in mirrors]


def export_eigenmode_visualization(
    project_path: str | Path,
    *,
    glyph_percentile: float = 98.0,
    bake_state: bool = True,
    pvpython: str | Path | None = None,
) -> dict:
    """Generate the ready-to-open ParaView session for stored eigenmodes.

    The eigenmode counterpart of :func:`export_run_visualization`.
    Eigenmodes belong to the project rather than to a run (they have no
    excitation and no time axis), so the artefacts sit in the project
    directory itself: ``paraview/eigenmodes/mode_*.vtr`` plus
    ``paraview/eigenmodes.pvd``, the pipeline script
    ``paraview_open.py`` and — when *bake_state* and ``pvpython`` is
    available — ``paraview.pvsm``.

    Stepping the ParaView time axis steps through the **modes**; each
    file carries its eigenfrequency as field data.  Fields are
    peak-normalised per mode (an eigenvector has no absolute
    amplitude), with the divisors stored alongside.

    Parameters
    ----------
    project_path : str or Path
        The project directory; must contain ``eigenmodes.h5``.
    glyph_percentile : float, default 98.0
        Percentile of ``|E|`` used as the glyph magnitude clip cap.
    bake_state : bool, default True
        Attempt the ``pvpython`` state bake.
    pvpython : str or Path or sequence of str, optional
        The ``pvpython`` that bakes the state file, when the machine
        carries more than one ParaView — a path, or the command that
        launches one (:func:`resolve_pvpython`).  Default:
        ``MAGNELIO_PVPYTHON``, else the first on ``PATH``.  The state is
        only good for the version that wrote it, so name the one that
        will open it.

    Returns
    -------
    dict
        Written artefact paths (``script``, ``state`` or ``None``,
        ``monitors``); empty when the project stores no eigenmodes.
    """
    from magnelio.io.project import Project  # noqa: PLC0415

    project = Project(project_path)
    if not (project.path / "eigenmodes.h5").exists():
        return {}
    mirrors = _symmetry_config(project)
    _ensure_geometry_vtm(project, mirrors)

    pv_dir = project.path / "paraview"
    pv_dir.mkdir(exist_ok=True)
    spec = _export_eigenmodes(project.path, pv_dir, project.grid, glyph_percentile)
    if spec is None:
        return {}

    geometry_rel, materials = _geometry_config(project.path, "geometry.vtm")
    _prepare_mirroring([spec], mirrors)
    config = {
        "geometry": geometry_rel,
        "materials": materials,
        "monitors": [spec],
        "symmetry": mirrors,
    }
    script = write_paraview_script(project.path / "paraview_open.py", config)
    state = project.path / "paraview.pvsm"
    baked = bake_state and bake_pvsm(script, state, pvpython=pvpython)
    return {
        "script": script,
        "state": state if baked else None,
        "monitors": ["eigenmodes"],
    }


def export_run_visualization(
    project_path: str | Path,
    run_name: str,
    *,
    glyph_percentile: float = 98.0,
    bake_state: bool = True,
    pvpython: str | Path | None = None,
) -> dict:
    """Generate the ready-to-open ParaView session for one stored run.

    Writes the tessellated ``geometry.vtm`` into the project directory
    when it is missing, and, under ``runs/<run_name>/``:

    * ``paraview/<monitor>.pvd`` + ``paraview/<monitor>/t_*.vtr`` — a
      field-time monitor's frames as a time series, averaged onto the
      cell centres from the staggered frames the store holds,
    * ``paraview/<monitor>.pvd`` + ``paraview/<monitor>/f_*.vtr`` — the
      frequency-monitor DFT as a frequency series,
    * ``paraview_open.py`` — the ``paraview.simple`` pipeline script,
    * ``paraview.pvsm`` — a double-clickable state file, when *bake_state*
      and ``pvpython`` is available.

    Parameters
    ----------
    project_path : str or Path
        The project directory.
    run_name : str
        Run subdirectory name under ``runs/``.
    glyph_percentile : float, default 98.0
        Percentile of ``|v|`` used as the glyph magnitude clip cap.
    bake_state : bool, default True
        Attempt the ``pvpython`` state bake.
    pvpython : str or Path or sequence of str, optional
        The ``pvpython`` that bakes the state file, when the machine
        carries more than one ParaView — a path, or the command that
        launches one (:func:`resolve_pvpython`).  Default:
        ``MAGNELIO_PVPYTHON``, else the first on ``PATH``.  The state is
        only good for the version that wrote it, so name the one that
        will open it.

    Returns
    -------
    dict
        Paths of the written artefacts (``script``, ``state`` or
        ``None``, ``monitors`` list); empty when there is nothing to
        visualise.
    """
    from magnelio.io.project import (  # noqa: PLC0415
        Project,
        _list_run_freq,
        _list_run_monitors,
    )

    project = Project(project_path)
    run_dir = project.path / "runs" / run_name
    if not run_dir.is_dir():
        raise FileNotFoundError(f"no such run directory: {run_dir}")
    mirrors = _symmetry_config(project)
    _ensure_geometry_vtm(project, mirrors)

    geometry_rel, materials = _geometry_config(project.path, "../../geometry.vtm")

    pv_dir = run_dir / "paraview"
    pv_dir.mkdir(exist_ok=True)

    monitors = []
    for name in _list_run_monitors(run_dir):
        spec = _export_time_monitor(run_dir, pv_dir, name, glyph_percentile)
        if spec is not None:
            monitors.append(spec)
    freq_names = _list_run_freq(run_dir)
    if freq_names:
        grid = project.grid
        for name in freq_names:
            spec = _export_freq_monitor(run_dir, pv_dir, name, grid, glyph_percentile)
            if spec is not None:
                monitors.append(spec)

    if not monitors and geometry_rel is None:
        return {}

    _prepare_mirroring(monitors, mirrors)
    config = {
        "geometry": geometry_rel,
        "materials": materials,
        "monitors": monitors,
        "symmetry": mirrors,
    }
    script = write_paraview_script(run_dir / "paraview_open.py", config)
    state = run_dir / "paraview.pvsm"
    baked = bake_state and bake_pvsm(script, state, pvpython=pvpython)
    return {
        "script": script,
        "state": state if baked else None,
        "monitors": [m["name"] for m in monitors],
    }
